var annotated_dup =
[
    [ "arion", "namespacearion.html", [
      [ "ABI_CALLING_CONVENTION", "structarion_1_1ABI__CALLING__CONVENTION.html", "structarion_1_1ABI__CALLING__CONVENTION" ],
      [ "ABI_REGISTERS", "structarion_1_1ABI__REGISTERS.html", "structarion_1_1ABI__REGISTERS" ],
      [ "ABI_SYSCALLING_CONVENTION", "structarion_1_1ABI__SYSCALLING__CONVENTION.html", "structarion_1_1ABI__SYSCALLING__CONVENTION" ],
      [ "ANALYSIS_HIT", "structarion_1_1ANALYSIS__HIT.html", "structarion_1_1ANALYSIS__HIT" ],
      [ "ARCH_ATTRIBUTES", "structarion_1_1ARCH__ATTRIBUTES.html", "structarion_1_1ARCH__ATTRIBUTES" ],
      [ "ArchManager", "classarion_1_1ArchManager.html", "classarion_1_1ArchManager" ],
      [ "Arion", "classarion_1_1Arion.html", "classarion_1_1Arion" ],
      [ "ARION_AFL_PARAM", "structarion_1_1ARION__AFL__PARAM.html", "structarion_1_1ARION__AFL__PARAM" ],
      [ "ARION_CONTEXT", "structarion_1_1ARION__CONTEXT.html", "structarion_1_1ARION__CONTEXT" ],
      [ "ARION_FILE", "structarion_1_1ARION__FILE.html", "structarion_1_1ARION__FILE" ],
      [ "ARION_FUTEX", "structarion_1_1ARION__FUTEX.html", "structarion_1_1ARION__FUTEX" ],
      [ "ARION_HOOK", "structarion_1_1ARION__HOOK.html", "structarion_1_1ARION__HOOK" ],
      [ "ARION_HOOK_PARAM", "structarion_1_1ARION__HOOK__PARAM.html", "structarion_1_1ARION__HOOK__PARAM" ],
      [ "ARION_MAPPING", "structarion_1_1ARION__MAPPING.html", "structarion_1_1ARION__MAPPING" ],
      [ "ARION_MEM_EDIT", "structarion_1_1ARION__MEM__EDIT.html", "structarion_1_1ARION__MEM__EDIT" ],
      [ "ARION_SOCKET", "structarion_1_1ARION__SOCKET.html", "structarion_1_1ARION__SOCKET" ],
      [ "ARION_TGROUP_ENTRY", "structarion_1_1ARION__TGROUP__ENTRY.html", "structarion_1_1ARION__TGROUP__ENTRY" ],
      [ "ARION_THREAD", "structarion_1_1ARION__THREAD.html", "structarion_1_1ARION__THREAD" ],
      [ "ArionAfl", "classarion_1_1ArionAfl.html", "classarion_1_1ArionAfl" ],
      [ "ArionGroup", "classarion_1_1ArionGroup.html", "classarion_1_1ArionGroup" ],
      [ "ARM_TRAP", "structarion_1_1ARM__TRAP.html", "structarion_1_1ARM__TRAP" ],
      [ "AUXV_PTRS", "structarion_1_1AUXV__PTRS.html", "structarion_1_1AUXV__PTRS" ],
      [ "BaremetalManager", "classarion_1_1BaremetalManager.html", "classarion_1_1BaremetalManager" ],
      [ "CODE_HIT", "structarion_1_1CODE__HIT.html", "structarion_1_1CODE__HIT" ],
      [ "CodeTraceAnalyzer", "classarion_1_1CodeTraceAnalyzer.html", "classarion_1_1CodeTraceAnalyzer" ],
      [ "CodeTraceComparator", "classarion_1_1CodeTraceComparator.html", "classarion_1_1CodeTraceComparator" ],
      [ "CodeTracer", "classarion_1_1CodeTracer.html", "classarion_1_1CodeTracer" ],
      [ "CodeTraceReader", "classarion_1_1CodeTraceReader.html", "classarion_1_1CodeTraceReader" ],
      [ "colorstream", "classarion_1_1colorstream.html", "classarion_1_1colorstream" ],
      [ "Config", "classarion_1_1Config.html", "classarion_1_1Config" ],
      [ "ContextManager", "classarion_1_1ContextManager.html", "classarion_1_1ContextManager" ],
      [ "ELF_COREDUMP_ATTRS", "structarion_1_1ELF__COREDUMP__ATTRS.html", "structarion_1_1ELF__COREDUMP__ATTRS" ],
      [ "ELF_COREDUMP_THREAD", "structarion_1_1ELF__COREDUMP__THREAD.html", "structarion_1_1ELF__COREDUMP__THREAD" ],
      [ "ELF_PARSER_ATTRIBUTES", "structarion_1_1ELF__PARSER__ATTRIBUTES.html", "structarion_1_1ELF__PARSER__ATTRIBUTES" ],
      [ "ElfCoredumpParser", "classarion_1_1ElfCoredumpParser.html", "classarion_1_1ElfCoredumpParser" ],
      [ "ElfLoader", "classarion_1_1ElfLoader.html", "classarion_1_1ElfLoader" ],
      [ "ElfParser", "classarion_1_1ElfParser.html", "classarion_1_1ElfParser" ],
      [ "EXECUTABLE_PARSER_ATTRIBUTES", "structarion_1_1EXECUTABLE__PARSER__ATTRIBUTES.html", "structarion_1_1EXECUTABLE__PARSER__ATTRIBUTES" ],
      [ "ExecutableParser", "classarion_1_1ExecutableParser.html", "classarion_1_1ExecutableParser" ],
      [ "FileSystemManager", "classarion_1_1FileSystemManager.html", "classarion_1_1FileSystemManager" ],
      [ "GdtManager", "classarion_1_1GdtManager.html", "classarion_1_1GdtManager" ],
      [ "HooksManager", "classarion_1_1HooksManager.html", "classarion_1_1HooksManager" ],
      [ "LinuxArchManager", "classarion_1_1LinuxArchManager.html", "classarion_1_1LinuxArchManager" ],
      [ "LinuxBaremetalLoader", "classarion_1_1LinuxBaremetalLoader.html", "classarion_1_1LinuxBaremetalLoader" ],
      [ "LinuxLoader", "classarion_1_1LinuxLoader.html", "classarion_1_1LinuxLoader" ],
      [ "LinuxSyscallManager", "classarion_1_1LinuxSyscallManager.html", "classarion_1_1LinuxSyscallManager" ],
      [ "LNX_LOADER_PARAMS", "structarion_1_1LNX__LOADER__PARAMS.html", "structarion_1_1LNX__LOADER__PARAMS" ],
      [ "Logger", "classarion_1_1Logger.html", "classarion_1_1Logger" ],
      [ "MD5_CTXT", "structarion_1_1MD5__CTXT.html", "structarion_1_1MD5__CTXT" ],
      [ "MemoryManager", "classarion_1_1MemoryManager.html", "classarion_1_1MemoryManager" ],
      [ "MemoryRecorder", "classarion_1_1MemoryRecorder.html", "classarion_1_1MemoryRecorder" ],
      [ "PARSED_COREDUMP_THREAD", "structarion_1_1PARSED__COREDUMP__THREAD.html", "structarion_1_1PARSED__COREDUMP__THREAD" ],
      [ "ProcFSManager", "classarion_1_1ProcFSManager.html", "classarion_1_1ProcFSManager" ],
      [ "RVAL", "unionarion_1_1RVAL.html", "unionarion_1_1RVAL" ],
      [ "SEGMENT", "structarion_1_1SEGMENT.html", "structarion_1_1SEGMENT" ],
      [ "SIGNAL", "structarion_1_1SIGNAL.html", "structarion_1_1SIGNAL" ],
      [ "SignalManager", "classarion_1_1SignalManager.html", "classarion_1_1SignalManager" ],
      [ "SocketManager", "classarion_1_1SocketManager.html", "classarion_1_1SocketManager" ],
      [ "SYSCALL_FUNC", "structarion_1_1SYSCALL__FUNC.html", "structarion_1_1SYSCALL__FUNC" ],
      [ "ThreadingManager", "classarion_1_1ThreadingManager.html", "classarion_1_1ThreadingManager" ],
      [ "TRACE_MODULE", "structarion_1_1TRACE__MODULE.html", "structarion_1_1TRACE__MODULE" ],
      [ "TRACER_MAPPING", "structarion_1_1TRACER__MAPPING.html", "structarion_1_1TRACER__MAPPING" ]
    ] ],
    [ "arion_arm", "namespacearion__arm.html", [
      [ "ArchManagerARM", "classarion__arm_1_1ArchManagerARM.html", "classarion__arm_1_1ArchManagerARM" ]
    ] ],
    [ "arion_arm64", "namespacearion__arm64.html", [
      [ "ArchManagerARM64", "classarion__arm64_1_1ArchManagerARM64.html", "classarion__arm64_1_1ArchManagerARM64" ]
    ] ],
    [ "arion_exception", "namespacearion__exception.html", [
      [ "ArionException", "classarion__exception_1_1ArionException.html", "classarion__exception_1_1ArionException" ],
      [ "BadLinkageTypeException", "classarion__exception_1_1BadLinkageTypeException.html", "classarion__exception_1_1BadLinkageTypeException" ],
      [ "CantReachTraceAddrException", "classarion__exception_1_1CantReachTraceAddrException.html", "classarion__exception_1_1CantReachTraceAddrException" ],
      [ "CantReachTraceOffException", "classarion__exception_1_1CantReachTraceOffException.html", "classarion__exception_1_1CantReachTraceOffException" ],
      [ "CantUnmapOutsideSegmentException", "classarion__exception_1_1CantUnmapOutsideSegmentException.html", "classarion__exception_1_1CantUnmapOutsideSegmentException" ],
      [ "CapstoneOpenException", "classarion__exception_1_1CapstoneOpenException.html", "classarion__exception_1_1CapstoneOpenException" ],
      [ "ConfigKeyNotFoundException", "classarion__exception_1_1ConfigKeyNotFoundException.html", "classarion__exception_1_1ConfigKeyNotFoundException" ],
      [ "ConfigWrongTypeAccessException", "classarion__exception_1_1ConfigWrongTypeAccessException.html", "classarion__exception_1_1ConfigWrongTypeAccessException" ],
      [ "DifferentTraceModesException", "classarion__exception_1_1DifferentTraceModesException.html", "classarion__exception_1_1DifferentTraceModesException" ],
      [ "ElfParsingException", "classarion__exception_1_1ElfParsingException.html", "classarion__exception_1_1ElfParsingException" ],
      [ "ExpiredWeakPtrException", "classarion__exception_1_1ExpiredWeakPtrException.html", "classarion__exception_1_1ExpiredWeakPtrException" ],
      [ "FileAlreadyHasFdException", "classarion__exception_1_1FileAlreadyHasFdException.html", "classarion__exception_1_1FileAlreadyHasFdException" ],
      [ "FileNotFoundException", "classarion__exception_1_1FileNotFoundException.html", "classarion__exception_1_1FileNotFoundException" ],
      [ "FileNotInFsException", "classarion__exception_1_1FileNotInFsException.html", "classarion__exception_1_1FileNotInFsException" ],
      [ "FileOpenException", "classarion__exception_1_1FileOpenException.html", "classarion__exception_1_1FileOpenException" ],
      [ "FileTooSmallException", "classarion__exception_1_1FileTooSmallException.html", "classarion__exception_1_1FileTooSmallException" ],
      [ "HeavierRegException", "classarion__exception_1_1HeavierRegException.html", "classarion__exception_1_1HeavierRegException" ],
      [ "InvalidArgumentException", "classarion__exception_1_1InvalidArgumentException.html", "classarion__exception_1_1InvalidArgumentException" ],
      [ "InvalidSyscallNameException", "classarion__exception_1_1InvalidSyscallNameException.html", "classarion__exception_1_1InvalidSyscallNameException" ],
      [ "InvalidSyscallNoException", "classarion__exception_1_1InvalidSyscallNoException.html", "classarion__exception_1_1InvalidSyscallNoException" ],
      [ "KeystoneAsmException", "classarion__exception_1_1KeystoneAsmException.html", "classarion__exception_1_1KeystoneAsmException" ],
      [ "KeystoneOpenException", "classarion__exception_1_1KeystoneOpenException.html", "classarion__exception_1_1KeystoneOpenException" ],
      [ "MemAlreadyMappedException", "classarion__exception_1_1MemAlreadyMappedException.html", "classarion__exception_1_1MemAlreadyMappedException" ],
      [ "MemoryRecorderAlreadyStartedException", "classarion__exception_1_1MemoryRecorderAlreadyStartedException.html", "classarion__exception_1_1MemoryRecorderAlreadyStartedException" ],
      [ "MemoryRecorderAlreadyStoppedException", "classarion__exception_1_1MemoryRecorderAlreadyStoppedException.html", "classarion__exception_1_1MemoryRecorderAlreadyStoppedException" ],
      [ "MultiplePrPsInfoNotesException", "classarion__exception_1_1MultiplePrPsInfoNotesException.html", "classarion__exception_1_1MultiplePrPsInfoNotesException" ],
      [ "NewerContextFileVersionException", "classarion__exception_1_1NewerContextFileVersionException.html", "classarion__exception_1_1NewerContextFileVersionException" ],
      [ "NewerTraceFileVersionException", "classarion__exception_1_1NewerTraceFileVersionException.html", "classarion__exception_1_1NewerTraceFileVersionException" ],
      [ "NoChildWithPidException", "classarion__exception_1_1NoChildWithPidException.html", "classarion__exception_1_1NoChildWithPidException" ],
      [ "NoCoredumpCurrentThreadException", "classarion__exception_1_1NoCoredumpCurrentThreadException.html", "classarion__exception_1_1NoCoredumpCurrentThreadException" ],
      [ "NoFileAtFdException", "classarion__exception_1_1NoFileAtFdException.html", "classarion__exception_1_1NoFileAtFdException" ],
      [ "NoFreeGdtEntryException", "classarion__exception_1_1NoFreeGdtEntryException.html", "classarion__exception_1_1NoFreeGdtEntryException" ],
      [ "NoIdtEntryWithIntnoException", "classarion__exception_1_1NoIdtEntryWithIntnoException.html", "classarion__exception_1_1NoIdtEntryWithIntnoException" ],
      [ "NoProcessWithPidException", "classarion__exception_1_1NoProcessWithPidException.html", "classarion__exception_1_1NoProcessWithPidException" ],
      [ "NoRegWithNameException", "classarion__exception_1_1NoRegWithNameException.html", "classarion__exception_1_1NoRegWithNameException" ],
      [ "NoRegWithValueException", "classarion__exception_1_1NoRegWithValueException.html", "classarion__exception_1_1NoRegWithValueException" ],
      [ "NoSegmentAtAddrException", "classarion__exception_1_1NoSegmentAtAddrException.html", "classarion__exception_1_1NoSegmentAtAddrException" ],
      [ "NoSegmentWithInfoException", "classarion__exception_1_1NoSegmentWithInfoException.html", "classarion__exception_1_1NoSegmentWithInfoException" ],
      [ "NoSighandlerForSignalException", "classarion__exception_1_1NoSighandlerForSignalException.html", "classarion__exception_1_1NoSighandlerForSignalException" ],
      [ "NoSignalForIntrException", "classarion__exception_1_1NoSignalForIntrException.html", "classarion__exception_1_1NoSignalForIntrException" ],
      [ "NoSocketAtFdException", "classarion__exception_1_1NoSocketAtFdException.html", "classarion__exception_1_1NoSocketAtFdException" ],
      [ "NoStructFieldWithNameException", "classarion__exception_1_1NoStructFieldWithNameException.html", "classarion__exception_1_1NoStructFieldWithNameException" ],
      [ "PathTooLongException", "classarion__exception_1_1PathTooLongException.html", "classarion__exception_1_1PathTooLongException" ],
      [ "ReadLinkFileException", "classarion__exception_1_1ReadLinkFileException.html", "classarion__exception_1_1ReadLinkFileException" ],
      [ "SegmentNotMappedException", "classarion__exception_1_1SegmentNotMappedException.html", "classarion__exception_1_1SegmentNotMappedException" ],
      [ "SocketAlreadyHasFdException", "classarion__exception_1_1SocketAlreadyHasFdException.html", "classarion__exception_1_1SocketAlreadyHasFdException" ],
      [ "ThreadAlreadySigWaitingException", "classarion__exception_1_1ThreadAlreadySigWaitingException.html", "classarion__exception_1_1ThreadAlreadySigWaitingException" ],
      [ "TooManyHooksException", "classarion__exception_1_1TooManyHooksException.html", "classarion__exception_1_1TooManyHooksException" ],
      [ "TooManyLoggersException", "classarion__exception_1_1TooManyLoggersException.html", "classarion__exception_1_1TooManyLoggersException" ],
      [ "TooManyStructsException", "classarion__exception_1_1TooManyStructsException.html", "classarion__exception_1_1TooManyStructsException" ],
      [ "TooManyThreadsException", "classarion__exception_1_1TooManyThreadsException.html", "classarion__exception_1_1TooManyThreadsException" ],
      [ "TracerAlreadyDisabledException", "classarion__exception_1_1TracerAlreadyDisabledException.html", "classarion__exception_1_1TracerAlreadyDisabledException" ],
      [ "TracerAlreadyEnabledException", "classarion__exception_1_1TracerAlreadyEnabledException.html", "classarion__exception_1_1TracerAlreadyEnabledException" ],
      [ "UnhandledSyncSignalException", "classarion__exception_1_1UnhandledSyncSignalException.html", "classarion__exception_1_1UnhandledSyncSignalException" ],
      [ "UnicornAflException", "classarion__exception_1_1UnicornAflException.html", "classarion__exception_1_1UnicornAflException" ],
      [ "UnicornAflNoExitsException", "classarion__exception_1_1UnicornAflNoExitsException.html", "classarion__exception_1_1UnicornAflNoExitsException" ],
      [ "UnicornCtlException", "classarion__exception_1_1UnicornCtlException.html", "classarion__exception_1_1UnicornCtlException" ],
      [ "UnicornCtlFlushTbException", "classarion__exception_1_1UnicornCtlFlushTbException.html", "classarion__exception_1_1UnicornCtlFlushTbException" ],
      [ "UnicornHookAddException", "classarion__exception_1_1UnicornHookAddException.html", "classarion__exception_1_1UnicornHookAddException" ],
      [ "UnicornHookDelException", "classarion__exception_1_1UnicornHookDelException.html", "classarion__exception_1_1UnicornHookDelException" ],
      [ "UnicornMapException", "classarion__exception_1_1UnicornMapException.html", "classarion__exception_1_1UnicornMapException" ],
      [ "UnicornMemProtectException", "classarion__exception_1_1UnicornMemProtectException.html", "classarion__exception_1_1UnicornMemProtectException" ],
      [ "UnicornMemReadException", "classarion__exception_1_1UnicornMemReadException.html", "classarion__exception_1_1UnicornMemReadException" ],
      [ "UnicornMemRegionsException", "classarion__exception_1_1UnicornMemRegionsException.html", "classarion__exception_1_1UnicornMemRegionsException" ],
      [ "UnicornMemWriteException", "classarion__exception_1_1UnicornMemWriteException.html", "classarion__exception_1_1UnicornMemWriteException" ],
      [ "UnicornOpenException", "classarion__exception_1_1UnicornOpenException.html", "classarion__exception_1_1UnicornOpenException" ],
      [ "UnicornRegReadException", "classarion__exception_1_1UnicornRegReadException.html", "classarion__exception_1_1UnicornRegReadException" ],
      [ "UnicornRegWriteException", "classarion__exception_1_1UnicornRegWriteException.html", "classarion__exception_1_1UnicornRegWriteException" ],
      [ "UnicornRunException", "classarion__exception_1_1UnicornRunException.html", "classarion__exception_1_1UnicornRunException" ],
      [ "UnicornStopException", "classarion__exception_1_1UnicornStopException.html", "classarion__exception_1_1UnicornStopException" ],
      [ "UnicornUnmapException", "classarion__exception_1_1UnicornUnmapException.html", "classarion__exception_1_1UnicornUnmapException" ],
      [ "UnknownLinkageTypeException", "classarion__exception_1_1UnknownLinkageTypeException.html", "classarion__exception_1_1UnknownLinkageTypeException" ],
      [ "UnknownSignalException", "classarion__exception_1_1UnknownSignalException.html", "classarion__exception_1_1UnknownSignalException" ],
      [ "UnknownTraceModeException", "classarion__exception_1_1UnknownTraceModeException.html", "classarion__exception_1_1UnknownTraceModeException" ],
      [ "UnknownTraceModuleHashException", "classarion__exception_1_1UnknownTraceModuleHashException.html", "classarion__exception_1_1UnknownTraceModuleHashException" ],
      [ "UnknownTraceModuleIdException", "classarion__exception_1_1UnknownTraceModuleIdException.html", "classarion__exception_1_1UnknownTraceModuleIdException" ],
      [ "UnknownTraceModuleNameException", "classarion__exception_1_1UnknownTraceModuleNameException.html", "classarion__exception_1_1UnknownTraceModuleNameException" ],
      [ "UnknownTraceRegException", "classarion__exception_1_1UnknownTraceRegException.html", "classarion__exception_1_1UnknownTraceRegException" ],
      [ "UnsupportedCpuArchException", "classarion__exception_1_1UnsupportedCpuArchException.html", "classarion__exception_1_1UnsupportedCpuArchException" ],
      [ "UnsupportedHostCpuArchException", "classarion__exception_1_1UnsupportedHostCpuArchException.html", "classarion__exception_1_1UnsupportedHostCpuArchException" ],
      [ "WaitSameProcessException", "classarion__exception_1_1WaitSameProcessException.html", "classarion__exception_1_1WaitSameProcessException" ],
      [ "WrongContextFileMagicException", "classarion__exception_1_1WrongContextFileMagicException.html", "classarion__exception_1_1WrongContextFileMagicException" ],
      [ "WrongHookIdException", "classarion__exception_1_1WrongHookIdException.html", "classarion__exception_1_1WrongHookIdException" ],
      [ "WrongHookParamsException", "classarion__exception_1_1WrongHookParamsException.html", "classarion__exception_1_1WrongHookParamsException" ],
      [ "WrongLogLevelException", "classarion__exception_1_1WrongLogLevelException.html", "classarion__exception_1_1WrongLogLevelException" ],
      [ "WrongStructIdException", "classarion__exception_1_1WrongStructIdException.html", "classarion__exception_1_1WrongStructIdException" ],
      [ "WrongThreadIdException", "classarion__exception_1_1WrongThreadIdException.html", "classarion__exception_1_1WrongThreadIdException" ],
      [ "WrongTraceFileMagicException", "classarion__exception_1_1WrongTraceFileMagicException.html", "classarion__exception_1_1WrongTraceFileMagicException" ],
      [ "WrongTraceModeException", "classarion__exception_1_1WrongTraceModeException.html", "classarion__exception_1_1WrongTraceModeException" ]
    ] ],
    [ "arion_lnx_arm", "namespacearion__lnx__arm.html", [
      [ "ArchManagerLinuxARM", "classarion__lnx__arm_1_1ArchManagerLinuxARM.html", "classarion__lnx__arm_1_1ArchManagerLinuxARM" ],
      [ "elf_prstatus", "structarion__lnx__arm_1_1elf__prstatus.html", "structarion__lnx__arm_1_1elf__prstatus" ],
      [ "fp_reg", "structarion__lnx__arm_1_1fp__reg.html", "structarion__lnx__arm_1_1fp__reg" ],
      [ "pt_regs", "structarion__lnx__arm_1_1pt__regs.html", "structarion__lnx__arm_1_1pt__regs" ],
      [ "user_fp", "structarion__lnx__arm_1_1user__fp.html", "structarion__lnx__arm_1_1user__fp" ]
    ] ],
    [ "arion_lnx_arm64", "namespacearion__lnx__arm64.html", [
      [ "ArchManagerLinuxARM64", "classarion__lnx__arm64_1_1ArchManagerLinuxARM64.html", "classarion__lnx__arm64_1_1ArchManagerLinuxARM64" ],
      [ "elf_prstatus", "structarion__lnx__arm64_1_1elf__prstatus.html", "structarion__lnx__arm64_1_1elf__prstatus" ],
      [ "frame_record", "structarion__lnx__arm64_1_1frame__record.html", "structarion__lnx__arm64_1_1frame__record" ],
      [ "frame_record_meta", "structarion__lnx__arm64_1_1frame__record__meta.html", "structarion__lnx__arm64_1_1frame__record__meta" ],
      [ "pt_regs", "structarion__lnx__arm64_1_1pt__regs.html", "structarion__lnx__arm64_1_1pt__regs" ],
      [ "user_fpsimd_state", "structarion__lnx__arm64_1_1user__fpsimd__state.html", "structarion__lnx__arm64_1_1user__fpsimd__state" ],
      [ "user_pt_regs", "structarion__lnx__arm64_1_1user__pt__regs.html", "structarion__lnx__arm64_1_1user__pt__regs" ]
    ] ],
    [ "arion_lnx_type", "namespacearion__lnx__type.html", [
      [ "__kernel_old_timeval", "structarion__lnx__type_1_1____kernel__old__timeval.html", "structarion__lnx__type_1_1____kernel__old__timeval" ],
      [ "AccessModeType", "classarion__lnx__type_1_1AccessModeType.html", "classarion__lnx__type_1_1AccessModeType" ],
      [ "CloneArgsStructFactory", "classarion__lnx__type_1_1CloneArgsStructFactory.html", "classarion__lnx__type_1_1CloneArgsStructFactory" ],
      [ "CloneFlagType", "classarion__lnx__type_1_1CloneFlagType.html", "classarion__lnx__type_1_1CloneFlagType" ],
      [ "elf_prstatus_common", "structarion__lnx__type_1_1elf__prstatus__common.html", "structarion__lnx__type_1_1elf__prstatus__common" ],
      [ "elf_siginfo", "structarion__lnx__type_1_1elf__siginfo.html", "structarion__lnx__type_1_1elf__siginfo" ],
      [ "ErrCodeType", "classarion__lnx__type_1_1ErrCodeType.html", "classarion__lnx__type_1_1ErrCodeType" ],
      [ "FileATFlagType", "classarion__lnx__type_1_1FileATFlagType.html", "classarion__lnx__type_1_1FileATFlagType" ],
      [ "FileDescriptorType", "classarion__lnx__type_1_1FileDescriptorType.html", "classarion__lnx__type_1_1FileDescriptorType" ],
      [ "FileModeType", "classarion__lnx__type_1_1FileModeType.html", "classarion__lnx__type_1_1FileModeType" ],
      [ "FutexOpType", "classarion__lnx__type_1_1FutexOpType.html", "classarion__lnx__type_1_1FutexOpType" ],
      [ "In6AddrTType", "classarion__lnx__type_1_1In6AddrTType.html", "classarion__lnx__type_1_1In6AddrTType" ],
      [ "InAddrTType", "classarion__lnx__type_1_1InAddrTType.html", "classarion__lnx__type_1_1InAddrTType" ],
      [ "iovec32", "structarion__lnx__type_1_1iovec32.html", "structarion__lnx__type_1_1iovec32" ],
      [ "ksigaction", "structarion__lnx__type_1_1ksigaction.html", "structarion__lnx__type_1_1ksigaction" ],
      [ "MmapFlagType", "classarion__lnx__type_1_1MmapFlagType.html", "classarion__lnx__type_1_1MmapFlagType" ],
      [ "OpenModeType", "classarion__lnx__type_1_1OpenModeType.html", "classarion__lnx__type_1_1OpenModeType" ],
      [ "ProtFlagType", "classarion__lnx__type_1_1ProtFlagType.html", "classarion__lnx__type_1_1ProtFlagType" ],
      [ "rlimit32", "structarion__lnx__type_1_1rlimit32.html", "structarion__lnx__type_1_1rlimit32" ],
      [ "SeekWhenceType", "classarion__lnx__type_1_1SeekWhenceType.html", "classarion__lnx__type_1_1SeekWhenceType" ],
      [ "SignalType", "classarion__lnx__type_1_1SignalType.html", "classarion__lnx__type_1_1SignalType" ],
      [ "SockaddrIn6StructFactory", "classarion__lnx__type_1_1SockaddrIn6StructFactory.html", "classarion__lnx__type_1_1SockaddrIn6StructFactory" ],
      [ "SockaddrInStructFactory", "classarion__lnx__type_1_1SockaddrInStructFactory.html", "classarion__lnx__type_1_1SockaddrInStructFactory" ],
      [ "SockaddrUnStructFactory", "classarion__lnx__type_1_1SockaddrUnStructFactory.html", "classarion__lnx__type_1_1SockaddrUnStructFactory" ],
      [ "SocketDomainType", "classarion__lnx__type_1_1SocketDomainType.html", "classarion__lnx__type_1_1SocketDomainType" ],
      [ "SocketTypeType", "classarion__lnx__type_1_1SocketTypeType.html", "classarion__lnx__type_1_1SocketTypeType" ],
      [ "StatStructFactory", "classarion__lnx__type_1_1StatStructFactory.html", "classarion__lnx__type_1_1StatStructFactory" ],
      [ "StatxAttrsType", "classarion__lnx__type_1_1StatxAttrsType.html", "classarion__lnx__type_1_1StatxAttrsType" ],
      [ "StatxMaskType", "classarion__lnx__type_1_1StatxMaskType.html", "classarion__lnx__type_1_1StatxMaskType" ],
      [ "StatxStructFactory", "classarion__lnx__type_1_1StatxStructFactory.html", "classarion__lnx__type_1_1StatxStructFactory" ],
      [ "StructCloneArgsType", "classarion__lnx__type_1_1StructCloneArgsType.html", "classarion__lnx__type_1_1StructCloneArgsType" ],
      [ "StructSockaddrIn6Type", "classarion__lnx__type_1_1StructSockaddrIn6Type.html", "classarion__lnx__type_1_1StructSockaddrIn6Type" ],
      [ "StructSockaddrInType", "classarion__lnx__type_1_1StructSockaddrInType.html", "classarion__lnx__type_1_1StructSockaddrInType" ],
      [ "StructSockaddrType", "classarion__lnx__type_1_1StructSockaddrType.html", "classarion__lnx__type_1_1StructSockaddrType" ],
      [ "StructSockaddrUnType", "classarion__lnx__type_1_1StructSockaddrUnType.html", "classarion__lnx__type_1_1StructSockaddrUnType" ],
      [ "StructStatType", "classarion__lnx__type_1_1StructStatType.html", "classarion__lnx__type_1_1StructStatType" ],
      [ "StructStatxType", "classarion__lnx__type_1_1StructStatxType.html", "classarion__lnx__type_1_1StructStatxType" ],
      [ "StructTimespecType", "classarion__lnx__type_1_1StructTimespecType.html", "classarion__lnx__type_1_1StructTimespecType" ],
      [ "TimespecStructFactory", "classarion__lnx__type_1_1TimespecStructFactory.html", "classarion__lnx__type_1_1TimespecStructFactory" ]
    ] ],
    [ "arion_lnx_x86", "namespacearion__lnx__x86.html", [
      [ "ArchManagerLinuxX86", "classarion__lnx__x86_1_1ArchManagerLinuxX86.html", "classarion__lnx__x86_1_1ArchManagerLinuxX86" ],
      [ "elf_prstatus", "structarion__lnx__x86_1_1elf__prstatus.html", "structarion__lnx__x86_1_1elf__prstatus" ],
      [ "user_i387_struct", "structarion__lnx__x86_1_1user__i387__struct.html", "structarion__lnx__x86_1_1user__i387__struct" ],
      [ "user_regs_struct", "structarion__lnx__x86_1_1user__regs__struct.html", "structarion__lnx__x86_1_1user__regs__struct" ]
    ] ],
    [ "arion_lnx_x86_64", "namespacearion__lnx__x86__64.html", [
      [ "ArchManagerLinuxX8664", "classarion__lnx__x86__64_1_1ArchManagerLinuxX8664.html", "classarion__lnx__x86__64_1_1ArchManagerLinuxX8664" ],
      [ "elf_prstatus", "structarion__lnx__x86__64_1_1elf__prstatus.html", "structarion__lnx__x86__64_1_1elf__prstatus" ],
      [ "user_i387_struct", "structarion__lnx__x86__64_1_1user__i387__struct.html", "structarion__lnx__x86__64_1_1user__i387__struct" ],
      [ "user_regs_struct", "structarion__lnx__x86__64_1_1user__regs__struct.html", "structarion__lnx__x86__64_1_1user__regs__struct" ]
    ] ],
    [ "arion_poly_struct", "namespacearion__poly__struct.html", [
      [ "AbsArionStructType", "classarion__poly__struct_1_1AbsArionStructType.html", "classarion__poly__struct_1_1AbsArionStructType" ],
      [ "ArionStructType", "classarion__poly__struct_1_1ArionStructType.html", "classarion__poly__struct_1_1ArionStructType" ],
      [ "ArionVariableStructType", "classarion__poly__struct_1_1ArionVariableStructType.html", "classarion__poly__struct_1_1ArionVariableStructType" ],
      [ "POLYMORPHIC_STRUCT_CONSTRAINT", "structarion__poly__struct_1_1POLYMORPHIC__STRUCT__CONSTRAINT.html", "structarion__poly__struct_1_1POLYMORPHIC__STRUCT__CONSTRAINT" ],
      [ "POLYMORPHIC_STRUCT_FIELD", "structarion__poly__struct_1_1POLYMORPHIC__STRUCT__FIELD.html", "structarion__poly__struct_1_1POLYMORPHIC__STRUCT__FIELD" ],
      [ "PolymorphicStruct", "classarion__poly__struct_1_1PolymorphicStruct.html", "classarion__poly__struct_1_1PolymorphicStruct" ],
      [ "PolymorphicStructFactory", "classarion__poly__struct_1_1PolymorphicStructFactory.html", "classarion__poly__struct_1_1PolymorphicStructFactory" ]
    ] ],
    [ "arion_type", "namespacearion__type.html", [
      [ "FlagType", "classarion__type_1_1FlagType.html", "classarion__type_1_1FlagType" ],
      [ "IntType", "classarion__type_1_1IntType.html", "classarion__type_1_1IntType" ],
      [ "KernelType", "classarion__type_1_1KernelType.html", "classarion__type_1_1KernelType" ],
      [ "KernelTypeRegistry", "classarion__type_1_1KernelTypeRegistry.html", "classarion__type_1_1KernelTypeRegistry" ],
      [ "RawStringType", "classarion__type_1_1RawStringType.html", "classarion__type_1_1RawStringType" ]
    ] ],
    [ "arion_x86", "namespacearion__x86.html", [
      [ "ArchManagerX86", "classarion__x86_1_1ArchManagerX86.html", "classarion__x86_1_1ArchManagerX86" ]
    ] ],
    [ "arion_x86_64", "namespacearion__x86__64.html", [
      [ "ArchManagerX8664", "classarion__x86__64_1_1ArchManagerX8664.html", "classarion__x86__64_1_1ArchManagerX8664" ]
    ] ]
];