FROM ubuntu:24.04 AS builder

ARG VERSION=1.0.0
ARG DEBIAN_FRONTEND="noninteractive"

RUN apt-get update -y && apt-get upgrade -y && apt-get install -y --no-install-recommends \
    git \
    gcc-multilib \
    g++-multilib \
    uuid-dev \
    python3 \
    pkg-config \
    clang \
    libclang-dev \
    build-essential \
    curl \
    dpkg-dev \
    fakeroot \
    libssl-dev \
    ca-certificates \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN curl -LO https://github.com/Kitware/CMake/releases/download/v3.28.2/cmake-3.28.2-linux-x86_64.tar.gz \
    && tar -zxvf cmake-3.28.2-linux-x86_64.tar.gz \
    && mv cmake-3.28.2-linux-x86_64 /opt/cmake \
    && rm cmake-3.28.2-linux-x86_64.tar.gz

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/opt/cmake/bin:/root/.cargo/bin:$PATH"

WORKDIR /app

COPY include ./include
COPY src ./src
COPY tools ./tools
COPY lib ./lib
COPY res ./res
COPY cmake ./cmake
COPY CMakeLists.txt .
COPY .gitmodules .

RUN cmake -DCMAKE_BUILD_TYPE=Release -B docker_build \
    && cmake --build docker_build --parallel 4 \
    && cmake --install docker_build --prefix /app/docker_build/install

RUN mkdir -p /app/docker_build/deb_package/DEBIAN \
    && mkdir -p /app/docker_build/deb_package/usr/include/arion \
    && mkdir -p /app/docker_build/deb_package/usr/lib \
    && cp -r /app/include/arion/* /app/docker_build/deb_package/usr/include/arion/ \
    && cp -r /app/lib/capstone/include/capstone /app/docker_build/deb_package/usr/include/arion/ \
    && cp -r /app/lib/keystone/include/keystone /app/docker_build/deb_package/usr/include/arion/ \
    && cp -r /app/lib/lief/include/LIEF /app/docker_build/deb_package/usr/include/arion/ \
    && cp -r /app/docker_build/lib/lief/include/LIEF/* /app/docker_build/deb_package/usr/include/arion/LIEF/ || true \
    && cp -r /app/lib/spdlog/include/spdlog /app/docker_build/deb_package/usr/include/arion/ \
    && cp -r /app/lib/unicorn/include/unicorn /app/docker_build/deb_package/usr/include/arion/ \
    && cp -r /app/lib/unicornafl/include/unicornafl /app/docker_build/deb_package/usr/include/arion/ \
    && cp -r /app/docker_build/libarion.so /app/docker_build/deb_package/usr/lib/ \
    && cp -r /app/docker_build/install/lib/cmake /app/docker_build/deb_package/usr/lib/ \
    && find /app/docker_build/deb_package/usr/include/ -type f -exec chmod 666 {} +

RUN echo "Package: arion" > /app/docker_build/deb_package/DEBIAN/control && \
    echo "Version: $VERSION" >> /app/docker_build/deb_package/DEBIAN/control && \
    echo "Section: libs" >> /app/docker_build/deb_package/DEBIAN/control && \
    echo "Priority: optional" >> /app/docker_build/deb_package/DEBIAN/control && \
    echo "Architecture: amd64" >> /app/docker_build/deb_package/DEBIAN/control && \
    echo "Depends: libc6, uuid-dev" >> /app/docker_build/deb_package/DEBIAN/control && \
    echo "Maintainer: HellDiner <me.helldiner@gmail.com>" >> /app/docker_build/deb_package/DEBIAN/control && \
    echo "Description: A high-performance C++ framework for emulating executable binaries." >> /app/docker_build/deb_package/DEBIAN/control

RUN dpkg-deb --build /app/docker_build/deb_package /app/docker_build/arion-$VERSION.deb

FROM scratch AS export
COPY --from=builder /app/docker_build/*.deb /app/docker_build/
