#ifndef ARION_ABI_ARM64_HPP
#define ARION_ABI_ARM64_HPP

#include <arion/common/abi_manager.hpp>
#include <arion/common/global_defs.hpp>

namespace arion_arm64
{
inline std::map<uint64_t, std::string> NAME_BY_SYSCALL_NO = {{0, "io_setup"},
                                                             {1, "io_destroy"},
                                                             {2, "io_submit"},
                                                             {3, "io_cancel"},
                                                             {4, "io_getevents"},
                                                             {5, "setxattr"},
                                                             {6, "lsetxattr"},
                                                             {7, "fsetxattr"},
                                                             {8, "getxattr"},
                                                             {9, "lgetxattr"},
                                                             {10, "fgetxattr"},
                                                             {11, "listxattr"},
                                                             {12, "llistxattr"},
                                                             {13, "flistxattr"},
                                                             {14, "removexattr"},
                                                             {15, "lremovexattr"},
                                                             {16, "fremovexattr"},
                                                             {17, "getcwd"},
                                                             {19, "eventfd2"},
                                                             {20, "epoll_create1"},
                                                             {21, "epoll_ctl"},
                                                             {22, "epoll_pwait"},
                                                             {23, "dup"},
                                                             {24, "dup3"},
                                                             {25, "fcntl"},
                                                             {26, "inotify_init1"},
                                                             {27, "inotify_add_watch"},
                                                             {28, "inotify_rm_watch"},
                                                             {29, "ioctl"},
                                                             {30, "ioprio_set"},
                                                             {31, "ioprio_get"},
                                                             {32, "flock"},
                                                             {33, "mknodat"},
                                                             {34, "mkdirat"},
                                                             {35, "unlinkat"},
                                                             {36, "symlinkat"},
                                                             {37, "linkat"},
                                                             {38, "renameat"},
                                                             {39, "umount"},
                                                             {40, "mount"},
                                                             {41, "pivot_root"},
                                                             {43, "statfs"},
                                                             {44, "fstatfs"},
                                                             {45, "truncate"},
                                                             {46, "ftruncate"},
                                                             {47, "fallocate"},
                                                             {48, "faccessat"},
                                                             {49, "chdir"},
                                                             {50, "fchdir"},
                                                             {51, "chroot"},
                                                             {52, "fchmod"},
                                                             {53, "fchmodat"},
                                                             {54, "fchownat"},
                                                             {55, "fchown"},
                                                             {56, "openat"},
                                                             {57, "close"},
                                                             {58, "vhangup"},
                                                             {59, "pipe2"},
                                                             {60, "quotactl"},
                                                             {61, "getdents64"},
                                                             {62, "lseek"},
                                                             {63, "read"},
                                                             {64, "write"},
                                                             {65, "readv"},
                                                             {66, "writev"},
                                                             {67, "pread64"},
                                                             {68, "pwrite64"},
                                                             {69, "preadv"},
                                                             {70, "pwritev"},
                                                             {71, "sendfile64"},
                                                             {72, "pselect6"},
                                                             {73, "ppoll"},
                                                             {74, "signalfd4"},
                                                             {75, "vmsplice"},
                                                             {76, "splice"},
                                                             {77, "tee"},
                                                             {78, "readlinkat"},
                                                             {79, "newfstatat"},
                                                             {80, "newfstat"},
                                                             {81, "sync"},
                                                             {82, "fsync"},
                                                             {83, "fdatasync"},
                                                             {84, "sync_file_range"},
                                                             {85, "timerfd_create"},
                                                             {86, "timerfd_settime"},
                                                             {87, "timerfd_gettime"},
                                                             {88, "utimensat"},
                                                             {89, "acct"},
                                                             {90, "capget"},
                                                             {91, "capset"},
                                                             {92, "personality"},
                                                             {93, "exit"},
                                                             {94, "exit_group"},
                                                             {95, "waitid"},
                                                             {96, "set_tid_address"},
                                                             {97, "unshare"},
                                                             {98, "futex"},
                                                             {99, "set_robust_list"},
                                                             {100, "get_robust_list"},
                                                             {101, "nanosleep"},
                                                             {102, "getitimer"},
                                                             {103, "setitimer"},
                                                             {104, "kexec_load"},
                                                             {105, "init_module"},
                                                             {106, "delete_module"},
                                                             {107, "timer_create"},
                                                             {108, "timer_gettime"},
                                                             {109, "timer_getoverrun"},
                                                             {110, "timer_settime"},
                                                             {111, "timer_delete"},
                                                             {112, "clock_settime"},
                                                             {113, "clock_gettime"},
                                                             {114, "clock_getres"},
                                                             {115, "clock_nanosleep"},
                                                             {116, "syslog"},
                                                             {117, "ptrace"},
                                                             {118, "sched_setparam"},
                                                             {119, "sched_setscheduler"},
                                                             {120, "sched_getscheduler"},
                                                             {121, "sched_getparam"},
                                                             {122, "sched_setaffinity"},
                                                             {123, "sched_getaffinity"},
                                                             {124, "sched_yield"},
                                                             {125, "sched_get_priority_max"},
                                                             {126, "sched_get_priority_min"},
                                                             {127, "sched_rr_get_interval"},
                                                             {128, "restart_syscall"},
                                                             {129, "kill"},
                                                             {130, "tkill"},
                                                             {131, "tgkill"},
                                                             {132, "sigaltstack"},
                                                             {133, "rt_sigsuspend"},
                                                             {134, "rt_sigaction"},
                                                             {135, "rt_sigprocmask"},
                                                             {136, "rt_sigpending"},
                                                             {137, "rt_sigtimedwait"},
                                                             {138, "rt_sigqueueinfo"},
                                                             {139, "rt_sigreturn"},
                                                             {140, "setpriority"},
                                                             {141, "getpriority"},
                                                             {142, "reboot"},
                                                             {143, "setregid"},
                                                             {144, "setgid"},
                                                             {145, "setreuid"},
                                                             {146, "setuid"},
                                                             {147, "setresuid"},
                                                             {148, "getresuid"},
                                                             {149, "setresgid"},
                                                             {150, "getresgid"},
                                                             {151, "setfsuid"},
                                                             {152, "setfsgid"},
                                                             {153, "times"},
                                                             {154, "setpgid"},
                                                             {155, "getpgid"},
                                                             {156, "getsid"},
                                                             {157, "setsid"},
                                                             {158, "getgroups"},
                                                             {159, "setgroups"},
                                                             {160, "newuname"},
                                                             {161, "sethostname"},
                                                             {162, "setdomainname"},
                                                             {163, "getrlimit"},
                                                             {164, "setrlimit"},
                                                             {165, "getrusage"},
                                                             {166, "umask"},
                                                             {167, "prctl"},
                                                             {168, "getcpu"},
                                                             {169, "gettimeofday"},
                                                             {170, "settimeofday"},
                                                             {171, "adjtimex"},
                                                             {172, "getpid"},
                                                             {173, "getppid"},
                                                             {174, "getuid"},
                                                             {175, "geteuid"},
                                                             {176, "getgid"},
                                                             {177, "getegid"},
                                                             {178, "gettid"},
                                                             {179, "sysinfo"},
                                                             {180, "mq_open"},
                                                             {181, "mq_unlink"},
                                                             {182, "mq_timedsend"},
                                                             {183, "mq_timedreceive"},
                                                             {184, "mq_notify"},
                                                             {185, "mq_getsetattr"},
                                                             {186, "msgget"},
                                                             {187, "msgctl"},
                                                             {188, "msgrcv"},
                                                             {189, "msgsnd"},
                                                             {190, "semget"},
                                                             {191, "semctl"},
                                                             {192, "semtimedop"},
                                                             {193, "semop"},
                                                             {194, "shmget"},
                                                             {195, "shmctl"},
                                                             {196, "shmat"},
                                                             {197, "shmdt"},
                                                             {198, "socket"},
                                                             {199, "socketpair"},
                                                             {200, "bind"},
                                                             {201, "listen"},
                                                             {202, "accept"},
                                                             {203, "connect"},
                                                             {204, "getsockname"},
                                                             {205, "getpeername"},
                                                             {206, "sendto"},
                                                             {207, "recvfrom"},
                                                             {208, "setsockopt"},
                                                             {209, "getsockopt"},
                                                             {210, "shutdown"},
                                                             {211, "sendmsg"},
                                                             {212, "recvmsg"},
                                                             {213, "readahead"},
                                                             {214, "brk"},
                                                             {215, "munmap"},
                                                             {216, "mremap"},
                                                             {217, "add_key"},
                                                             {218, "request_key"},
                                                             {219, "keyctl"},
                                                             {220, "clone"},
                                                             {221, "execve"},
                                                             {222, "mmap"},
                                                             {223, "fadvise64_64"},
                                                             {224, "swapon"},
                                                             {225, "swapoff"},
                                                             {226, "mprotect"},
                                                             {227, "msync"},
                                                             {228, "mlock"},
                                                             {229, "munlock"},
                                                             {230, "mlockall"},
                                                             {231, "munlockall"},
                                                             {232, "mincore"},
                                                             {233, "madvise"},
                                                             {234, "remap_file_pages"},
                                                             {235, "mbind"},
                                                             {236, "get_mempolicy"},
                                                             {237, "set_mempolicy"},
                                                             {238, "migrate_pages"},
                                                             {239, "move_pages"},
                                                             {240, "rt_tgsigqueueinfo"},
                                                             {241, "perf_event_open"},
                                                             {242, "accept4"},
                                                             {243, "recvmmsg"},
                                                             {260, "wait4"},
                                                             {261, "prlimit64"},
                                                             {262, "fanotify_init"},
                                                             {263, "fanotify_mark"},
                                                             {264, "name_to_handle_at"},
                                                             {265, "open_by_handle_at"},
                                                             {266, "clock_adjtime"},
                                                             {267, "syncfs"},
                                                             {268, "setns"},
                                                             {269, "sendmmsg"},
                                                             {270, "process_vm_readv"},
                                                             {271, "process_vm_writev"},
                                                             {272, "kcmp"},
                                                             {273, "finit_module"},
                                                             {274, "sched_setattr"},
                                                             {275, "sched_getattr"},
                                                             {276, "renameat2"},
                                                             {277, "seccomp"},
                                                             {278, "getrandom"},
                                                             {279, "memfd_create"},
                                                             {280, "bpf"},
                                                             {281, "execveat"},
                                                             {282, "userfaultfd"},
                                                             {283, "membarrier"},
                                                             {284, "mlock2"},
                                                             {285, "copy_file_range"},
                                                             {286, "preadv2"},
                                                             {287, "pwritev2"},
                                                             {288, "pkey_mprotect"},
                                                             {289, "pkey_alloc"},
                                                             {290, "pkey_free"},
                                                             {291, "statx"},
                                                             {292, "io_pgetevents"},
                                                             {293, "rseq"},
                                                             {294, "kexec_file_load"},
                                                             {424, "pidfd_send_signal"},
                                                             {425, "io_uring_setup"},
                                                             {426, "io_uring_enter"},
                                                             {427, "io_uring_register"},
                                                             {428, "open_tree"},
                                                             {429, "move_mount"},
                                                             {430, "fsopen"},
                                                             {431, "fsconfig"},
                                                             {432, "fsmount"},
                                                             {433, "fspick"},
                                                             {434, "pidfd_open"},
                                                             {435, "clone3"},
                                                             {436, "close_range"},
                                                             {437, "openat2"},
                                                             {438, "pidfd_getfd"},
                                                             {439, "faccessat2"},
                                                             {440, "process_madvise"},
                                                             {441, "epoll_pwait2"},
                                                             {442, "mount_setattr"},
                                                             {443, "quotactl_fd"},
                                                             {444, "landlock_create_ruleset"},
                                                             {445, "landlock_add_rule"},
                                                             {446, "landlock_restrict_self"},
                                                             {447, "memfd_secret"},
                                                             {448, "process_mrelease"},
                                                             {449, "futex_waitv"},
                                                             {450, "set_mempolicy_home_node"},
                                                             {451, "cachestat"},
                                                             {452, "fchmodat2"},
                                                             {453, "map_shadow_stack"},
                                                             {454, "futex_wake"},
                                                             {455, "futex_wait"},
                                                             {456, "futex_requeue"},
                                                             {457, "statmount"},
                                                             {458, "listmount"},
                                                             {459, "lsm_get_self_attr"},
                                                             {460, "lsm_set_self_attr"},
                                                             {461, "lsm_list_modules"},
                                                             {462, "mseal"},
                                                             {463, "setxattrat"},
                                                             {464, "getxattrat"},
                                                             {465, "listxattrat"},
                                                             {466, "removexattrat"}};

inline std::map<std::string, arion::REG> ARCH_REGS = {
    {"X29", UC_ARM64_REG_X29},   {"X30", UC_ARM64_REG_X30},
    {"NZCV", UC_ARM64_REG_NZCV}, {"SP", UC_ARM64_REG_SP},
    {"WSP", UC_ARM64_REG_WSP},   {"WZR", UC_ARM64_REG_WZR},
    {"XZR", UC_ARM64_REG_XZR},   {"B0", UC_ARM64_REG_B0},
    {"B1", UC_ARM64_REG_B1},     {"B2", UC_ARM64_REG_B2},
    {"B3", UC_ARM64_REG_B3},     {"B4", UC_ARM64_REG_B4},
    {"B5", UC_ARM64_REG_B5},     {"B6", UC_ARM64_REG_B6},
    {"B7", UC_ARM64_REG_B7},     {"B8", UC_ARM64_REG_B8},
    {"B9", UC_ARM64_REG_B9},     {"B10", UC_ARM64_REG_B10},
    {"B11", UC_ARM64_REG_B11},   {"B12", UC_ARM64_REG_B12},
    {"B13", UC_ARM64_REG_B13},   {"B14", UC_ARM64_REG_B14},
    {"B15", UC_ARM64_REG_B15},   {"B16", UC_ARM64_REG_B16},
    {"B17", UC_ARM64_REG_B17},   {"B18", UC_ARM64_REG_B18},
    {"B19", UC_ARM64_REG_B19},   {"B20", UC_ARM64_REG_B20},
    {"B21", UC_ARM64_REG_B21},   {"B22", UC_ARM64_REG_B22},
    {"B23", UC_ARM64_REG_B23},   {"B24", UC_ARM64_REG_B24},
    {"B25", UC_ARM64_REG_B25},   {"B26", UC_ARM64_REG_B26},
    {"B27", UC_ARM64_REG_B27},   {"B28", UC_ARM64_REG_B28},
    {"B29", UC_ARM64_REG_B29},   {"B30", UC_ARM64_REG_B30},
    {"B31", UC_ARM64_REG_B31},   {"D0", UC_ARM64_REG_D0},
    {"D1", UC_ARM64_REG_D1},     {"D2", UC_ARM64_REG_D2},
    {"D3", UC_ARM64_REG_D3},     {"D4", UC_ARM64_REG_D4},
    {"D5", UC_ARM64_REG_D5},     {"D6", UC_ARM64_REG_D6},
    {"D7", UC_ARM64_REG_D7},     {"D8", UC_ARM64_REG_D8},
    {"D9", UC_ARM64_REG_D9},     {"D10", UC_ARM64_REG_D10},
    {"D11", UC_ARM64_REG_D11},   {"D12", UC_ARM64_REG_D12},
    {"D13", UC_ARM64_REG_D13},   {"D14", UC_ARM64_REG_D14},
    {"D15", UC_ARM64_REG_D15},   {"D16", UC_ARM64_REG_D16},
    {"D17", UC_ARM64_REG_D17},   {"D18", UC_ARM64_REG_D18},
    {"D19", UC_ARM64_REG_D19},   {"D20", UC_ARM64_REG_D20},
    {"D21", UC_ARM64_REG_D21},   {"D22", UC_ARM64_REG_D22},
    {"D23", UC_ARM64_REG_D23},   {"D24", UC_ARM64_REG_D24},
    {"D25", UC_ARM64_REG_D25},   {"D26", UC_ARM64_REG_D26},
    {"D27", UC_ARM64_REG_D27},   {"D28", UC_ARM64_REG_D28},
    {"D29", UC_ARM64_REG_D29},   {"D30", UC_ARM64_REG_D30},
    {"D31", UC_ARM64_REG_D31},   {"H0", UC_ARM64_REG_H0},
    {"H1", UC_ARM64_REG_H1},     {"H2", UC_ARM64_REG_H2},
    {"H3", UC_ARM64_REG_H3},     {"H4", UC_ARM64_REG_H4},
    {"H5", UC_ARM64_REG_H5},     {"H6", UC_ARM64_REG_H6},
    {"H7", UC_ARM64_REG_H7},     {"H8", UC_ARM64_REG_H8},
    {"H9", UC_ARM64_REG_H9},     {"H10", UC_ARM64_REG_H10},
    {"H11", UC_ARM64_REG_H11},   {"H12", UC_ARM64_REG_H12},
    {"H13", UC_ARM64_REG_H13},   {"H14", UC_ARM64_REG_H14},
    {"H15", UC_ARM64_REG_H15},   {"H16", UC_ARM64_REG_H16},
    {"H17", UC_ARM64_REG_H17},   {"H18", UC_ARM64_REG_H18},
    {"H19", UC_ARM64_REG_H19},   {"H20", UC_ARM64_REG_H20},
    {"H21", UC_ARM64_REG_H21},   {"H22", UC_ARM64_REG_H22},
    {"H23", UC_ARM64_REG_H23},   {"H24", UC_ARM64_REG_H24},
    {"H25", UC_ARM64_REG_H25},   {"H26", UC_ARM64_REG_H26},
    {"H27", UC_ARM64_REG_H27},   {"H28", UC_ARM64_REG_H28},
    {"H29", UC_ARM64_REG_H29},   {"H30", UC_ARM64_REG_H30},
    {"H31", UC_ARM64_REG_H31},   {"Q0", UC_ARM64_REG_Q0},
    {"Q1", UC_ARM64_REG_Q1},     {"Q2", UC_ARM64_REG_Q2},
    {"Q3", UC_ARM64_REG_Q3},     {"Q4", UC_ARM64_REG_Q4},
    {"Q5", UC_ARM64_REG_Q5},     {"Q6", UC_ARM64_REG_Q6},
    {"Q7", UC_ARM64_REG_Q7},     {"Q8", UC_ARM64_REG_Q8},
    {"Q9", UC_ARM64_REG_Q9},     {"Q10", UC_ARM64_REG_Q10},
    {"Q11", UC_ARM64_REG_Q11},   {"Q12", UC_ARM64_REG_Q12},
    {"Q13", UC_ARM64_REG_Q13},   {"Q14", UC_ARM64_REG_Q14},
    {"Q15", UC_ARM64_REG_Q15},   {"Q16", UC_ARM64_REG_Q16},
    {"Q17", UC_ARM64_REG_Q17},   {"Q18", UC_ARM64_REG_Q18},
    {"Q19", UC_ARM64_REG_Q19},   {"Q20", UC_ARM64_REG_Q20},
    {"Q21", UC_ARM64_REG_Q21},   {"Q22", UC_ARM64_REG_Q22},
    {"Q23", UC_ARM64_REG_Q23},   {"Q24", UC_ARM64_REG_Q24},
    {"Q25", UC_ARM64_REG_Q25},   {"Q26", UC_ARM64_REG_Q26},
    {"Q27", UC_ARM64_REG_Q27},   {"Q28", UC_ARM64_REG_Q28},
    {"Q29", UC_ARM64_REG_Q29},   {"Q30", UC_ARM64_REG_Q30},
    {"Q31", UC_ARM64_REG_Q31},   {"S0", UC_ARM64_REG_S0},
    {"S1", UC_ARM64_REG_S1},     {"S2", UC_ARM64_REG_S2},
    {"S3", UC_ARM64_REG_S3},     {"S4", UC_ARM64_REG_S4},
    {"S5", UC_ARM64_REG_S5},     {"S6", UC_ARM64_REG_S6},
    {"S7", UC_ARM64_REG_S7},     {"S8", UC_ARM64_REG_S8},
    {"S9", UC_ARM64_REG_S9},     {"S10", UC_ARM64_REG_S10},
    {"S11", UC_ARM64_REG_S11},   {"S12", UC_ARM64_REG_S12},
    {"S13", UC_ARM64_REG_S13},   {"S14", UC_ARM64_REG_S14},
    {"S15", UC_ARM64_REG_S15},   {"S16", UC_ARM64_REG_S16},
    {"S17", UC_ARM64_REG_S17},   {"S18", UC_ARM64_REG_S18},
    {"S19", UC_ARM64_REG_S19},   {"S20", UC_ARM64_REG_S20},
    {"S21", UC_ARM64_REG_S21},   {"S22", UC_ARM64_REG_S22},
    {"S23", UC_ARM64_REG_S23},   {"S24", UC_ARM64_REG_S24},
    {"S25", UC_ARM64_REG_S25},   {"S26", UC_ARM64_REG_S26},
    {"S27", UC_ARM64_REG_S27},   {"S28", UC_ARM64_REG_S28},
    {"S29", UC_ARM64_REG_S29},   {"S30", UC_ARM64_REG_S30},
    {"S31", UC_ARM64_REG_S31},   {"W0", UC_ARM64_REG_W0},
    {"W1", UC_ARM64_REG_W1},     {"W2", UC_ARM64_REG_W2},
    {"W3", UC_ARM64_REG_W3},     {"W4", UC_ARM64_REG_W4},
    {"W5", UC_ARM64_REG_W5},     {"W6", UC_ARM64_REG_W6},
    {"W7", UC_ARM64_REG_W7},     {"W8", UC_ARM64_REG_W8},
    {"W9", UC_ARM64_REG_W9},     {"W10", UC_ARM64_REG_W10},
    {"W11", UC_ARM64_REG_W11},   {"W12", UC_ARM64_REG_W12},
    {"W13", UC_ARM64_REG_W13},   {"W14", UC_ARM64_REG_W14},
    {"W15", UC_ARM64_REG_W15},   {"W16", UC_ARM64_REG_W16},
    {"W17", UC_ARM64_REG_W17},   {"W18", UC_ARM64_REG_W18},
    {"W19", UC_ARM64_REG_W19},   {"W20", UC_ARM64_REG_W20},
    {"W21", UC_ARM64_REG_W21},   {"W22", UC_ARM64_REG_W22},
    {"W23", UC_ARM64_REG_W23},   {"W24", UC_ARM64_REG_W24},
    {"W25", UC_ARM64_REG_W25},   {"W26", UC_ARM64_REG_W26},
    {"W27", UC_ARM64_REG_W27},   {"W28", UC_ARM64_REG_W28},
    {"W29", UC_ARM64_REG_W29},   {"W30", UC_ARM64_REG_W30},
    {"X0", UC_ARM64_REG_X0},     {"X1", UC_ARM64_REG_X1},
    {"X2", UC_ARM64_REG_X2},     {"X3", UC_ARM64_REG_X3},
    {"X4", UC_ARM64_REG_X4},     {"X5", UC_ARM64_REG_X5},
    {"X6", UC_ARM64_REG_X6},     {"X7", UC_ARM64_REG_X7},
    {"X8", UC_ARM64_REG_X8},     {"X9", UC_ARM64_REG_X9},
    {"X10", UC_ARM64_REG_X10},   {"X11", UC_ARM64_REG_X11},
    {"X12", UC_ARM64_REG_X12},   {"X13", UC_ARM64_REG_X13},
    {"X14", UC_ARM64_REG_X14},   {"X15", UC_ARM64_REG_X15},
    {"X16", UC_ARM64_REG_X16},   {"X17", UC_ARM64_REG_X17},
    {"X18", UC_ARM64_REG_X18},   {"X19", UC_ARM64_REG_X19},
    {"X20", UC_ARM64_REG_X20},   {"X21", UC_ARM64_REG_X21},
    {"X22", UC_ARM64_REG_X22},   {"X23", UC_ARM64_REG_X23},
    {"X24", UC_ARM64_REG_X24},   {"X25", UC_ARM64_REG_X25},
    {"X26", UC_ARM64_REG_X26},   {"X27", UC_ARM64_REG_X27},
    {"X28", UC_ARM64_REG_X28},   {"V0", UC_ARM64_REG_V0},
    {"V1", UC_ARM64_REG_V1},     {"V2", UC_ARM64_REG_V2},
    {"V3", UC_ARM64_REG_V3},     {"V4", UC_ARM64_REG_V4},
    {"V5", UC_ARM64_REG_V5},     {"V6", UC_ARM64_REG_V6},
    {"V7", UC_ARM64_REG_V7},     {"V8", UC_ARM64_REG_V8},
    {"V9", UC_ARM64_REG_V9},     {"V10", UC_ARM64_REG_V10},
    {"V11", UC_ARM64_REG_V11},   {"V12", UC_ARM64_REG_V12},
    {"V13", UC_ARM64_REG_V13},   {"V14", UC_ARM64_REG_V14},
    {"V15", UC_ARM64_REG_V15},   {"V16", UC_ARM64_REG_V16},
    {"V17", UC_ARM64_REG_V17},   {"V18", UC_ARM64_REG_V18},
    {"V19", UC_ARM64_REG_V19},   {"V20", UC_ARM64_REG_V20},
    {"V21", UC_ARM64_REG_V21},   {"V22", UC_ARM64_REG_V22},
    {"V23", UC_ARM64_REG_V23},   {"V24", UC_ARM64_REG_V24},
    {"V25", UC_ARM64_REG_V25},   {"V26", UC_ARM64_REG_V26},
    {"V27", UC_ARM64_REG_V27},   {"V28", UC_ARM64_REG_V28},
    {"V29", UC_ARM64_REG_V29},   {"V30", UC_ARM64_REG_V30},
    {"V31", UC_ARM64_REG_V31},   {"PC", UC_ARM64_REG_PC},
    {"CP", UC_ARM64_REG_CP_REG}, {"CPACR_EL1", UC_ARM64_REG_CPACR_EL1},
    {"FPCR", UC_ARM64_REG_FPCR}, {"FPSR", UC_ARM64_REG_FPSR}};

inline std::map<arion::REG, uint8_t> ARCH_REGS_SZ = {
    {UC_ARM64_REG_B0, 1},   {UC_ARM64_REG_B1, 1},   {UC_ARM64_REG_B2, 1},      {UC_ARM64_REG_B3, 1},
    {UC_ARM64_REG_B4, 1},   {UC_ARM64_REG_B5, 1},   {UC_ARM64_REG_B6, 1},      {UC_ARM64_REG_B7, 1},
    {UC_ARM64_REG_B8, 1},   {UC_ARM64_REG_B9, 1},   {UC_ARM64_REG_B10, 1},     {UC_ARM64_REG_B11, 1},
    {UC_ARM64_REG_B12, 1},  {UC_ARM64_REG_B13, 1},  {UC_ARM64_REG_B14, 1},     {UC_ARM64_REG_B15, 1},
    {UC_ARM64_REG_B16, 1},  {UC_ARM64_REG_B17, 1},  {UC_ARM64_REG_B18, 1},     {UC_ARM64_REG_B19, 1},
    {UC_ARM64_REG_B20, 1},  {UC_ARM64_REG_B21, 1},  {UC_ARM64_REG_B22, 1},     {UC_ARM64_REG_B23, 1},
    {UC_ARM64_REG_B24, 1},  {UC_ARM64_REG_B25, 1},  {UC_ARM64_REG_B26, 1},     {UC_ARM64_REG_B27, 1},
    {UC_ARM64_REG_B28, 1},  {UC_ARM64_REG_B29, 1},  {UC_ARM64_REG_B30, 1},     {UC_ARM64_REG_B31, 1},
    {UC_ARM64_REG_H0, 2},   {UC_ARM64_REG_H1, 2},   {UC_ARM64_REG_H2, 2},      {UC_ARM64_REG_H3, 2},
    {UC_ARM64_REG_H4, 2},   {UC_ARM64_REG_H5, 2},   {UC_ARM64_REG_H6, 2},      {UC_ARM64_REG_H7, 2},
    {UC_ARM64_REG_H8, 2},   {UC_ARM64_REG_H9, 2},   {UC_ARM64_REG_H10, 2},     {UC_ARM64_REG_H11, 2},
    {UC_ARM64_REG_H12, 2},  {UC_ARM64_REG_H13, 2},  {UC_ARM64_REG_H14, 2},     {UC_ARM64_REG_H15, 2},
    {UC_ARM64_REG_H16, 2},  {UC_ARM64_REG_H17, 2},  {UC_ARM64_REG_H18, 2},     {UC_ARM64_REG_H19, 2},
    {UC_ARM64_REG_H20, 2},  {UC_ARM64_REG_H21, 2},  {UC_ARM64_REG_H22, 2},     {UC_ARM64_REG_H23, 2},
    {UC_ARM64_REG_H24, 2},  {UC_ARM64_REG_H25, 2},  {UC_ARM64_REG_H26, 2},     {UC_ARM64_REG_H27, 2},
    {UC_ARM64_REG_H28, 2},  {UC_ARM64_REG_H29, 2},  {UC_ARM64_REG_H30, 2},     {UC_ARM64_REG_H31, 2},
    {UC_ARM64_REG_S0, 4},   {UC_ARM64_REG_S1, 4},   {UC_ARM64_REG_S2, 4},      {UC_ARM64_REG_S3, 4},
    {UC_ARM64_REG_S4, 4},   {UC_ARM64_REG_S5, 4},   {UC_ARM64_REG_S6, 4},      {UC_ARM64_REG_S7, 4},
    {UC_ARM64_REG_S8, 4},   {UC_ARM64_REG_S9, 4},   {UC_ARM64_REG_S10, 4},     {UC_ARM64_REG_S11, 4},
    {UC_ARM64_REG_S12, 4},  {UC_ARM64_REG_S13, 4},  {UC_ARM64_REG_S14, 4},     {UC_ARM64_REG_S15, 4},
    {UC_ARM64_REG_S16, 4},  {UC_ARM64_REG_S17, 4},  {UC_ARM64_REG_S18, 4},     {UC_ARM64_REG_S19, 4},
    {UC_ARM64_REG_S20, 4},  {UC_ARM64_REG_S21, 4},  {UC_ARM64_REG_S22, 4},     {UC_ARM64_REG_S23, 4},
    {UC_ARM64_REG_S24, 4},  {UC_ARM64_REG_S25, 4},  {UC_ARM64_REG_S26, 4},     {UC_ARM64_REG_S27, 4},
    {UC_ARM64_REG_S28, 4},  {UC_ARM64_REG_S29, 4},  {UC_ARM64_REG_S30, 4},     {UC_ARM64_REG_S31, 4},
    {UC_ARM64_REG_X0, 8},   {UC_ARM64_REG_X1, 8},   {UC_ARM64_REG_X2, 8},      {UC_ARM64_REG_X3, 8},
    {UC_ARM64_REG_X4, 8},   {UC_ARM64_REG_X5, 8},   {UC_ARM64_REG_X6, 8},      {UC_ARM64_REG_X7, 8},
    {UC_ARM64_REG_X8, 8},   {UC_ARM64_REG_X9, 8},   {UC_ARM64_REG_X10, 8},     {UC_ARM64_REG_X11, 8},
    {UC_ARM64_REG_X12, 8},  {UC_ARM64_REG_X13, 8},  {UC_ARM64_REG_X14, 8},     {UC_ARM64_REG_X15, 8},
    {UC_ARM64_REG_X16, 8},  {UC_ARM64_REG_X17, 8},  {UC_ARM64_REG_X18, 8},     {UC_ARM64_REG_X19, 8},
    {UC_ARM64_REG_X20, 8},  {UC_ARM64_REG_X21, 8},  {UC_ARM64_REG_X22, 8},     {UC_ARM64_REG_X23, 8},
    {UC_ARM64_REG_X24, 8},  {UC_ARM64_REG_X25, 8},  {UC_ARM64_REG_X26, 8},     {UC_ARM64_REG_X27, 8},
    {UC_ARM64_REG_X28, 8},  {UC_ARM64_REG_X29, 8},  {UC_ARM64_REG_X30, 8},     {UC_ARM64_REG_SP, 8},
    {UC_ARM64_REG_XZR, 8},  {UC_ARM64_REG_WZR, 4},  {UC_ARM64_REG_WSP, 4},     {UC_ARM64_REG_W0, 4},
    {UC_ARM64_REG_W1, 4},   {UC_ARM64_REG_W2, 4},   {UC_ARM64_REG_W3, 4},      {UC_ARM64_REG_W4, 4},
    {UC_ARM64_REG_W5, 4},   {UC_ARM64_REG_W6, 4},   {UC_ARM64_REG_W7, 4},      {UC_ARM64_REG_W8, 4},
    {UC_ARM64_REG_W9, 4},   {UC_ARM64_REG_W10, 4},  {UC_ARM64_REG_W11, 4},     {UC_ARM64_REG_W12, 4},
    {UC_ARM64_REG_W13, 4},  {UC_ARM64_REG_W14, 4},  {UC_ARM64_REG_W15, 4},     {UC_ARM64_REG_W16, 4},
    {UC_ARM64_REG_W17, 4},  {UC_ARM64_REG_W18, 4},  {UC_ARM64_REG_W19, 4},     {UC_ARM64_REG_W20, 4},
    {UC_ARM64_REG_W21, 4},  {UC_ARM64_REG_W22, 4},  {UC_ARM64_REG_W23, 4},     {UC_ARM64_REG_W24, 4},
    {UC_ARM64_REG_W25, 4},  {UC_ARM64_REG_W26, 4},  {UC_ARM64_REG_W27, 4},     {UC_ARM64_REG_W28, 4},
    {UC_ARM64_REG_W29, 4},  {UC_ARM64_REG_W30, 4},  {UC_ARM64_REG_V0, 16},     {UC_ARM64_REG_V1, 16},
    {UC_ARM64_REG_V2, 16},  {UC_ARM64_REG_V3, 16},  {UC_ARM64_REG_V4, 16},     {UC_ARM64_REG_V5, 16},
    {UC_ARM64_REG_V6, 16},  {UC_ARM64_REG_V7, 16},  {UC_ARM64_REG_V8, 16},     {UC_ARM64_REG_V9, 16},
    {UC_ARM64_REG_V10, 16}, {UC_ARM64_REG_V11, 16}, {UC_ARM64_REG_V12, 16},    {UC_ARM64_REG_V13, 16},
    {UC_ARM64_REG_V14, 16}, {UC_ARM64_REG_V15, 16}, {UC_ARM64_REG_V16, 16},    {UC_ARM64_REG_V17, 16},
    {UC_ARM64_REG_V18, 16}, {UC_ARM64_REG_V19, 16}, {UC_ARM64_REG_V20, 16},    {UC_ARM64_REG_V21, 16},
    {UC_ARM64_REG_V22, 16}, {UC_ARM64_REG_V23, 16}, {UC_ARM64_REG_V24, 16},    {UC_ARM64_REG_V25, 16},
    {UC_ARM64_REG_V26, 16}, {UC_ARM64_REG_V27, 16}, {UC_ARM64_REG_V28, 16},    {UC_ARM64_REG_V29, 16},
    {UC_ARM64_REG_V30, 16}, {UC_ARM64_REG_V31, 16}, {UC_ARM64_REG_Q0, 16},     {UC_ARM64_REG_Q1, 16},
    {UC_ARM64_REG_Q2, 16},  {UC_ARM64_REG_Q3, 16},  {UC_ARM64_REG_Q4, 16},     {UC_ARM64_REG_Q5, 16},
    {UC_ARM64_REG_Q6, 16},  {UC_ARM64_REG_Q7, 16},  {UC_ARM64_REG_Q8, 16},     {UC_ARM64_REG_Q9, 16},
    {UC_ARM64_REG_Q10, 16}, {UC_ARM64_REG_Q11, 16}, {UC_ARM64_REG_Q12, 16},    {UC_ARM64_REG_Q13, 16},
    {UC_ARM64_REG_Q14, 16}, {UC_ARM64_REG_Q15, 16}, {UC_ARM64_REG_Q16, 16},    {UC_ARM64_REG_Q17, 16},
    {UC_ARM64_REG_Q18, 16}, {UC_ARM64_REG_Q19, 16}, {UC_ARM64_REG_Q20, 16},    {UC_ARM64_REG_Q21, 16},
    {UC_ARM64_REG_Q22, 16}, {UC_ARM64_REG_Q23, 16}, {UC_ARM64_REG_Q24, 16},    {UC_ARM64_REG_Q25, 16},
    {UC_ARM64_REG_Q26, 16}, {UC_ARM64_REG_Q27, 16}, {UC_ARM64_REG_Q28, 16},    {UC_ARM64_REG_Q29, 16},
    {UC_ARM64_REG_Q30, 16}, {UC_ARM64_REG_Q31, 16}, {UC_ARM64_REG_D0, 8},      {UC_ARM64_REG_D1, 8},
    {UC_ARM64_REG_D2, 8},   {UC_ARM64_REG_D3, 8},   {UC_ARM64_REG_D4, 8},      {UC_ARM64_REG_D5, 8},
    {UC_ARM64_REG_D6, 8},   {UC_ARM64_REG_D7, 8},   {UC_ARM64_REG_D8, 8},      {UC_ARM64_REG_D9, 8},
    {UC_ARM64_REG_D10, 8},  {UC_ARM64_REG_D11, 8},  {UC_ARM64_REG_D12, 8},     {UC_ARM64_REG_D13, 8},
    {UC_ARM64_REG_D14, 8},  {UC_ARM64_REG_D15, 8},  {UC_ARM64_REG_D16, 8},     {UC_ARM64_REG_D17, 8},
    {UC_ARM64_REG_D18, 8},  {UC_ARM64_REG_D19, 8},  {UC_ARM64_REG_D20, 8},     {UC_ARM64_REG_D21, 8},
    {UC_ARM64_REG_D22, 8},  {UC_ARM64_REG_D23, 8},  {UC_ARM64_REG_D24, 8},     {UC_ARM64_REG_D25, 8},
    {UC_ARM64_REG_D26, 8},  {UC_ARM64_REG_D27, 8},  {UC_ARM64_REG_D28, 8},     {UC_ARM64_REG_D29, 8},
    {UC_ARM64_REG_D30, 8},  {UC_ARM64_REG_D31, 8},  {UC_ARM64_REG_NZCV, 4},    {UC_ARM64_REG_FPCR, 4},
    {UC_ARM64_REG_FPSR, 4}, {UC_ARM64_REG_PC, 8},   {UC_ARM64_REG_CP_REG, 32}, {UC_ARM64_REG_CPACR_EL1, 4}};

inline std::vector<arion::REG> CTXT_REGS = {
    UC_ARM64_REG_X0,  UC_ARM64_REG_X1,  UC_ARM64_REG_X2,  UC_ARM64_REG_X3,   UC_ARM64_REG_X4,   UC_ARM64_REG_X5,
    UC_ARM64_REG_X6,  UC_ARM64_REG_X7,  UC_ARM64_REG_X8,  UC_ARM64_REG_X9,   UC_ARM64_REG_X10,  UC_ARM64_REG_X11,
    UC_ARM64_REG_X12, UC_ARM64_REG_X13, UC_ARM64_REG_X14, UC_ARM64_REG_X15,  UC_ARM64_REG_X16,  UC_ARM64_REG_X17,
    UC_ARM64_REG_X18, UC_ARM64_REG_X19, UC_ARM64_REG_X20, UC_ARM64_REG_X21,  UC_ARM64_REG_X22,  UC_ARM64_REG_X23,
    UC_ARM64_REG_X24, UC_ARM64_REG_X25, UC_ARM64_REG_X26, UC_ARM64_REG_X27,  UC_ARM64_REG_X28,  UC_ARM64_REG_X29,
    UC_ARM64_REG_X30, UC_ARM64_REG_SP,  UC_ARM64_REG_PC,  UC_ARM64_REG_NZCV, UC_ARM64_REG_FPCR, UC_ARM64_REG_FPSR,

    UC_ARM64_REG_V0,  UC_ARM64_REG_V1,  UC_ARM64_REG_V2,  UC_ARM64_REG_V3,   UC_ARM64_REG_V4,   UC_ARM64_REG_V5,
    UC_ARM64_REG_V6,  UC_ARM64_REG_V7,  UC_ARM64_REG_V8,  UC_ARM64_REG_V9,   UC_ARM64_REG_V10,  UC_ARM64_REG_V11,
    UC_ARM64_REG_V12, UC_ARM64_REG_V13, UC_ARM64_REG_V14, UC_ARM64_REG_V15,  UC_ARM64_REG_V16,  UC_ARM64_REG_V17,
    UC_ARM64_REG_V18, UC_ARM64_REG_V19, UC_ARM64_REG_V20, UC_ARM64_REG_V21,  UC_ARM64_REG_V22,  UC_ARM64_REG_V23,
    UC_ARM64_REG_V24, UC_ARM64_REG_V25, UC_ARM64_REG_V26, UC_ARM64_REG_V27,  UC_ARM64_REG_V28,  UC_ARM64_REG_V29,
    UC_ARM64_REG_V30, UC_ARM64_REG_V31};

inline std::map<uint64_t, CPU_INTR> IDT = {/*{1, UDEF},
                                           {2, SWI},
                                           {3, PREFETCH_ABORT},
                                           {4, DATA_ABORT},
                                           {5, IRQ},
                                           {6, FIQ},
                                           {7, BKPT},
                                           {8, EXCEPTION_EXIT},
                                           {9, KERNEL_TRAP},
                                           {11, HVC},
                                           {12, HYP_TRAP},
                                           {13, SMC},
                                           {14, VIRQ},
                                           {15, VFIQ},
                                           {16, SEMIHOST},
                                           {17, NOCP},
                                           {18, INVSTATE},
                                           {19, STKOF},
                                           {20, LAZYFP},
                                           {21, LSERR},
                                           {22, UNALIGNED}*/};

inline ABI_REGISTERS ABI_REGS = ABI_REGISTERS(UC_ARM64_REG_PC, UC_ARM64_REG_SP);

inline ABI_CALLING_CONVENTION ABI_CALLING_CONV =
    ABI_CALLING_CONVENTION(UC_ARM64_REG_X0, {UC_ARM64_REG_X0, UC_ARM64_REG_X1, UC_ARM64_REG_X2, UC_ARM64_REG_X3,
                                             UC_ARM64_REG_X4, UC_ARM64_REG_X5, UC_ARM64_REG_X6, UC_ARM64_REG_X7});

inline ABI_SYSCALLING_CONVENTION ABI_SYSCALLING_CONV = ABI_SYSCALLING_CONVENTION(
    UC_ARM64_REG_X8, UC_ARM64_REG_X0,
    {UC_ARM64_REG_X0, UC_ARM64_REG_X1, UC_ARM64_REG_X2, UC_ARM64_REG_X3, UC_ARM64_REG_X4, UC_ARM64_REG_X5});

inline arion::KERNEL_SEG_FLAGS SEG_FLAGS = 0;

inline uint32_t HWCAP2 = 0;

inline uint32_t HWCAP = 0x78bfafd;

inline const size_t PTR_SZ = 8;

inline const uint16_t ARCH_SZ = 64;

inline std::string ARCH_NAME = "ARM64";

inline arion::CPU_ARCH ARCH = arion::CPU_ARCH::ARM64_ARCH;

inline ABI_ATTRIBUTES ABI_ATTRS = ABI_ATTRIBUTES(ARCH, ARCH_NAME, ARCH_SZ, PTR_SZ, HWCAP, HWCAP2, SEG_FLAGS, ABI_REGS,
                                                 ABI_CALLING_CONV, ABI_SYSCALLING_CONV, NAME_BY_SYSCALL_NO);
}; // namespace arion_arm64

class AbiManagerARM64 : public AbiManager
{
  private:
    static void int_hook(std::shared_ptr<Arion> arion, uint32_t intno, void *user_data);
    void enable_lse();
    void enable_vfp();
    void setup();

  public:
    AbiManagerARM64()
        : AbiManager(std::make_shared<ABI_ATTRIBUTES>(arion_arm64::ABI_ATTRS), arion_arm64::ARCH_REGS,
                     arion_arm64::ARCH_REGS_SZ, arion_arm64::CTXT_REGS, arion_arm64::IDT, true) {};

    ks_engine *curr_ks();
    csh *curr_cs();
    arion::ADDR dump_tls();
    void load_tls(arion::ADDR new_tls);
};

#endif // ARION_ABI_ARM64_HPP
