#ifndef ARION_ARCH_ARM_HPP
#define ARION_ARCH_ARM_HPP

#include <arion/common/arch_manager.hpp>
#include <arion/common/global_defs.hpp>
#include <arion/platforms/linux/lnx_kernel_utils.hpp>
#include <cstdint>
#include <map>
#include <string>

#define ARION_ARM_MODE 0
#define ARION_THUMB_MODE 1

#define ARION_ARM_CPSR_THUMB_BIT (1 << 5)

namespace arion_arm
{

/// A map identifying an ARM syscall name given its number.
inline std::map<uint64_t, std::string> NAME_BY_SYSCALL_NO = {{0, "restart_syscall"},
                                                             {1, "exit"},
                                                             {2, "fork"},
                                                             {3, "read"},
                                                             {4, "write"},
                                                             {5, "open"},
                                                             {6, "close"},
                                                             {8, "creat"},
                                                             {9, "link"},
                                                             {10, "unlink"},
                                                             {11, "execve"},
                                                             {12, "chdir"},
                                                             {14, "mknod"},
                                                             {15, "chmod"},
                                                             {16, "lchown16"},
                                                             {19, "lseek"},
                                                             {20, "getpid"},
                                                             {21, "mount"},
                                                             {23, "setuid16"},
                                                             {24, "getuid16"},
                                                             {26, "ptrace"},
                                                             {29, "pause"},
                                                             {33, "access"},
                                                             {34, "nice"},
                                                             {36, "sync"},
                                                             {37, "kill"},
                                                             {38, "rename"},
                                                             {39, "mkdir"},
                                                             {40, "rmdir"},
                                                             {41, "dup"},
                                                             {42, "pipe"},
                                                             {43, "times"},
                                                             {45, "brk"},
                                                             {46, "setgid16"},
                                                             {47, "getgid16"},
                                                             {49, "geteuid16"},
                                                             {50, "getegid16"},
                                                             {51, "acct"},
                                                             {52, "umount"},
                                                             {54, "ioctl"},
                                                             {55, "fcntl"},
                                                             {57, "setpgid"},
                                                             {60, "umask"},
                                                             {61, "chroot"},
                                                             {62, "ustat"},
                                                             {63, "dup2"},
                                                             {64, "getppid"},
                                                             {65, "getpgrp"},
                                                             {66, "setsid"},
                                                             {67, "sigaction"},
                                                             {70, "setreuid16"},
                                                             {71, "setregid16"},
                                                             {72, "sigsuspend"},
                                                             {73, "sigpending"},
                                                             {74, "sethostname"},
                                                             {75, "setrlimit"},
                                                             {77, "getrusage"},
                                                             {78, "gettimeofday"},
                                                             {79, "settimeofday"},
                                                             {80, "getgroups16"},
                                                             {81, "setgroups16"},
                                                             {83, "symlink"},
                                                             {85, "readlink"},
                                                             {86, "uselib"},
                                                             {87, "swapon"},
                                                             {88, "reboot"},
                                                             {91, "munmap"},
                                                             {92, "truncate"},
                                                             {93, "ftruncate"},
                                                             {94, "fchmod"},
                                                             {95, "fchown16"},
                                                             {96, "getpriority"},
                                                             {97, "setpriority"},
                                                             {99, "statfs"},
                                                             {100, "fstatfs"},
                                                             {103, "syslog"},
                                                             {104, "setitimer"},
                                                             {105, "getitimer"},
                                                             {106, "newstat"},
                                                             {107, "newlstat"},
                                                             {108, "newfstat"},
                                                             {111, "vhangup"},
                                                             {114, "wait4"},
                                                             {115, "swapoff"},
                                                             {116, "sysinfo"},
                                                             {118, "fsync"},
                                                             {119, "sigreturn"},
                                                             {120, "clone"},
                                                             {121, "setdomainname"},
                                                             {122, "newuname"},
                                                             {124, "adjtimex"},
                                                             {125, "mprotect"},
                                                             {126, "sigprocmask"},
                                                             {128, "init_module"},
                                                             {129, "delete_module"},
                                                             {131, "quotactl"},
                                                             {132, "getpgid"},
                                                             {133, "fchdir"},
                                                             {135, "sysfs"},
                                                             {136, "personality"},
                                                             {138, "setfsuid16"},
                                                             {139, "setfsgid16"},
                                                             {140, "llseek"},
                                                             {141, "getdents"},
                                                             {142, "select"},
                                                             {143, "flock"},
                                                             {144, "msync"},
                                                             {145, "readv"},
                                                             {146, "writev"},
                                                             {147, "getsid"},
                                                             {148, "fdatasync"},
                                                             {150, "mlock"},
                                                             {151, "munlock"},
                                                             {152, "mlockall"},
                                                             {153, "munlockall"},
                                                             {154, "sched_setparam"},
                                                             {155, "sched_getparam"},
                                                             {156, "sched_setscheduler"},
                                                             {157, "sched_getscheduler"},
                                                             {158, "sched_yield"},
                                                             {159, "sched_get_priority_max"},
                                                             {160, "sched_get_priority_min"},
                                                             {161, "sched_rr_get_interval"},
                                                             {162, "nanosleep"},
                                                             {163, "mremap"},
                                                             {164, "setresuid16"},
                                                             {165, "getresuid16"},
                                                             {168, "poll"},
                                                             {170, "setresgid16"},
                                                             {171, "getresgid16"},
                                                             {172, "prctl"},
                                                             {173, "rt_sigreturn"},
                                                             {174, "rt_sigaction"},
                                                             {175, "rt_sigprocmask"},
                                                             {176, "rt_sigpending"},
                                                             {177, "rt_sigtimedwait"},
                                                             {178, "rt_sigqueueinfo"},
                                                             {179, "rt_sigsuspend"},
                                                             {180, "pread64"},
                                                             {181, "pwrite64"},
                                                             {182, "chown16"},
                                                             {183, "getcwd"},
                                                             {184, "capget"},
                                                             {185, "capset"},
                                                             {186, "sigaltstack"},
                                                             {187, "sendfile"},
                                                             {190, "vfork"},
                                                             {191, "getrlimit"},
                                                             {192, "mmap2"},
                                                             {193, "truncate64"},
                                                             {194, "ftruncate64"},
                                                             {195, "stat64"},
                                                             {196, "lstat64"},
                                                             {197, "fstat64"},
                                                             {198, "lchown"},
                                                             {199, "getuid"},
                                                             {200, "getgid"},
                                                             {201, "geteuid"},
                                                             {202, "getegid"},
                                                             {203, "setreuid"},
                                                             {204, "setregid"},
                                                             {205, "getgroups"},
                                                             {206, "setgroups"},
                                                             {207, "fchown"},
                                                             {208, "setresuid"},
                                                             {209, "getresuid"},
                                                             {210, "setresgid"},
                                                             {211, "getresgid"},
                                                             {212, "chown"},
                                                             {213, "setuid"},
                                                             {214, "setgid"},
                                                             {215, "setfsuid"},
                                                             {216, "setfsgid"},
                                                             {217, "getdents64"},
                                                             {218, "pivot_root"},
                                                             {219, "mincore"},
                                                             {220, "madvise"},
                                                             {221, "fcntl64"},
                                                             {224, "gettid"},
                                                             {225, "readahead"},
                                                             {226, "setxattr"},
                                                             {227, "lsetxattr"},
                                                             {228, "fsetxattr"},
                                                             {229, "getxattr"},
                                                             {230, "lgetxattr"},
                                                             {231, "fgetxattr"},
                                                             {232, "listxattr"},
                                                             {233, "llistxattr"},
                                                             {234, "flistxattr"},
                                                             {235, "removexattr"},
                                                             {236, "lremovexattr"},
                                                             {237, "fremovexattr"},
                                                             {238, "tkill"},
                                                             {239, "sendfile64"},
                                                             {240, "futex"},
                                                             {241, "sched_setaffinity"},
                                                             {242, "sched_getaffinity"},
                                                             {243, "io_setup"},
                                                             {244, "io_destroy"},
                                                             {245, "io_getevents"},
                                                             {246, "io_submit"},
                                                             {247, "io_cancel"},
                                                             {248, "exit_group"},
                                                             {250, "epoll_create"},
                                                             {251, "epoll_ctl"},
                                                             {252, "epoll_wait"},
                                                             {253, "remap_file_pages"},
                                                             {256, "set_tid_address"},
                                                             {257, "timer_create"},
                                                             {258, "timer_settime"},
                                                             {259, "timer_gettime"},
                                                             {260, "timer_getoverrun"},
                                                             {261, "timer_delete"},
                                                             {262, "clock_settime"},
                                                             {263, "clock_gettime"},
                                                             {264, "clock_getres"},
                                                             {265, "clock_nanosleep"},
                                                             {266, "statfs64"},
                                                             {267, "fstatfs64"},
                                                             {268, "tgkill"},
                                                             {269, "utimes"},
                                                             {270, "fadvise64_64"},
                                                             {272, "pciconfig_read"},
                                                             {273, "pciconfig_write"},
                                                             {274, "mq_open"},
                                                             {275, "mq_unlink"},
                                                             {276, "mq_timedsend"},
                                                             {277, "mq_timedreceive"},
                                                             {278, "mq_notify"},
                                                             {279, "mq_getsetattr"},
                                                             {280, "waitid"},
                                                             {281, "socket"},
                                                             {282, "bind"},
                                                             {283, "connect"},
                                                             {284, "listen"},
                                                             {285, "accept"},
                                                             {286, "getsockname"},
                                                             {287, "getpeername"},
                                                             {288, "socketpair"},
                                                             {289, "send"},
                                                             {290, "sendto"},
                                                             {291, "recv"},
                                                             {292, "recvfrom"},
                                                             {293, "shutdown"},
                                                             {294, "setsockopt"},
                                                             {295, "getsockopt"},
                                                             {296, "sendmsg"},
                                                             {297, "recvmsg"},
                                                             {298, "semop"},
                                                             {299, "semget"},
                                                             {300, "semctl"},
                                                             {301, "msgsnd"},
                                                             {302, "msgrcv"},
                                                             {303, "msgget"},
                                                             {304, "msgctl"},
                                                             {305, "shmat"},
                                                             {306, "shmdt"},
                                                             {307, "shmget"},
                                                             {308, "shmctl"},
                                                             {309, "add_key"},
                                                             {310, "request_key"},
                                                             {311, "keyctl"},
                                                             {312, "semtimedop"},
                                                             {314, "ioprio_set"},
                                                             {315, "ioprio_get"},
                                                             {316, "inotify_init"},
                                                             {317, "inotify_add_watch"},
                                                             {318, "inotify_rm_watch"},
                                                             {322, "openat"},
                                                             {323, "mkdirat"},
                                                             {324, "mknodat"},
                                                             {325, "fchownat"},
                                                             {326, "futimesat"},
                                                             {327, "fstatat64"},
                                                             {328, "unlinkat"},
                                                             {329, "renameat"},
                                                             {330, "linkat"},
                                                             {331, "symlinkat"},
                                                             {332, "readlinkat"},
                                                             {333, "fchmodat"},
                                                             {334, "faccessat"},
                                                             {335, "pselect6"},
                                                             {336, "ppoll"},
                                                             {337, "unshare"},
                                                             {338, "set_robust_list"},
                                                             {339, "get_robust_list"},
                                                             {340, "splice"},
                                                             {341, "sync_file_range2"},
                                                             {342, "tee"},
                                                             {343, "vmsplice"},
                                                             {345, "getcpu"},
                                                             {346, "epoll_pwait"},
                                                             {347, "kexec_load"},
                                                             {348, "utimensat"},
                                                             {349, "signalfd"},
                                                             {350, "timerfd_create"},
                                                             {351, "eventfd"},
                                                             {352, "fallocate"},
                                                             {353, "timerfd_settime"},
                                                             {354, "timerfd_gettime"},
                                                             {355, "signalfd4"},
                                                             {356, "eventfd2"},
                                                             {357, "epoll_create1"},
                                                             {358, "dup3"},
                                                             {359, "pipe2"},
                                                             {360, "inotify_init1"},
                                                             {361, "preadv"},
                                                             {362, "pwritev"},
                                                             {363, "rt_tgsigqueueinfo"},
                                                             {364, "perf_event_open"},
                                                             {365, "recvmmsg"},
                                                             {366, "accept4"},
                                                             {367, "fanotify_init"},
                                                             {368, "fanotify_mark"},
                                                             {369, "prlimit64"},
                                                             {370, "name_to_handle_at"},
                                                             {371, "open_by_handle_at"},
                                                             {372, "clock_adjtime"},
                                                             {373, "syncfs"},
                                                             {374, "sendmmsg"},
                                                             {375, "setns"},
                                                             {376, "process_vm_readv"},
                                                             {377, "process_vm_writev"},
                                                             {378, "kcmp"},
                                                             {379, "finit_module"},
                                                             {380, "sched_setattr"},
                                                             {381, "sched_getattr"},
                                                             {382, "renameat2"},
                                                             {383, "seccomp"},
                                                             {384, "getrandom"},
                                                             {385, "memfd_create"},
                                                             {386, "bpf"},
                                                             {387, "execveat"},
                                                             {388, "userfaultfd"},
                                                             {389, "membarrier"},
                                                             {390, "mlock2"},
                                                             {391, "copy_file_range"},
                                                             {392, "preadv2"},
                                                             {393, "pwritev2"},
                                                             {397, "statx"},
                                                             {398, "rseq"},
                                                             {399, "io_pgetevents"},
                                                             {403, "clock_gettime"},
                                                             {404, "clock_settime"},
                                                             {405, "clock_adjtime"},
                                                             {406, "clock_getres"},
                                                             {407, "clock_nanosleep"},
                                                             {408, "timer_gettime"},
                                                             {409, "timer_settime"},
                                                             {410, "timerfd_gettime"},
                                                             {411, "timerfd_settime"},
                                                             {412, "utimensat"},
                                                             {413, "pselect6"},
                                                             {414, "ppoll"},
                                                             {416, "io_pgetevents"},
                                                             {417, "recvmmsg"},
                                                             {418, "mq_timedsend"},
                                                             {419, "mq_timedreceive"},
                                                             {420, "semtimedop"},
                                                             {421, "rt_sigtimedwait"},
                                                             {422, "futex_time64"},
                                                             {423, "sched_rr_get_interval"},
                                                             {424, "pidfd_send_signal"},
                                                             {425, "io_uring_setup"},
                                                             {426, "io_uring_enter"},
                                                             {427, "io_uring_register"},
                                                             {428, "open_tree"},
                                                             {429, "move_mount"},
                                                             {430, "fsopen"},
                                                             {431, "fsconfig"},
                                                             {432, "fsmount"},
                                                             {433, "fspick"},
                                                             {434, "pidfd_open"},
                                                             {435, "clone3"},
                                                             {436, "close_range"},
                                                             {437, "openat2"},
                                                             {438, "pidfd_getfd"},
                                                             {439, "faccessat2"},
                                                             {440, "process_madvise"},
                                                             {441, "epoll_pwait2"},
                                                             {442, "mount_setattr"},
                                                             {443, "quotactl_fd"},
                                                             {444, "landlock_create_ruleset"},
                                                             {445, "landlock_add_rule"},
                                                             {446, "landlock_restrict_self"},
                                                             {448, "process_mrelease"},
                                                             {449, "futex_waitv"},
                                                             {451, "cachestat"},
                                                             {452, "fchmodat2"},
                                                             {454, "futex_wake"},
                                                             {455, "futex_wait"},
                                                             {456, "futex_requeue"},
                                                             {457, "statmount"},
                                                             {458, "listmount"},
                                                             {459, "lsm_get_self_attr"},
                                                             {460, "lsm_set_self_attr"},
                                                             {461, "lsm_list_modules"},
                                                             {463, "setxattrat"},
                                                             {464, "getxattrat"},
                                                             {465, "listxattrat"},
                                                             {466, "removexattrat"},
                                                             {983041, "breakpoint"},
                                                             {983042, "cacheflush"},
                                                             {983043, "usr26"},
                                                             {983044, "usr32"},
                                                             {983045, "set_tls"},
                                                             {983046, "get_tls"}};

/// A map identifying a Unicorn ARM register given its name.
inline std::map<std::string, arion::REG> ARCH_REGS = {{"APSR", UC_ARM_REG_APSR},
                                                      {"APSR_NZCV", UC_ARM_REG_APSR_NZCV},
                                                      {"CPSR", UC_ARM_REG_CPSR},
                                                      {"FPEXC", UC_ARM_REG_FPEXC},
                                                      {"FPSCR", UC_ARM_REG_FPSCR},
                                                      {"FPSID", UC_ARM_REG_FPSID},
                                                      {"LR", UC_ARM_REG_LR},
                                                      {"PC", UC_ARM_REG_PC},
                                                      {"SP", UC_ARM_REG_SP},
                                                      {"SPSR", UC_ARM_REG_SPSR},
                                                      {"D0", UC_ARM_REG_D0},
                                                      {"D1", UC_ARM_REG_D1},
                                                      {"D2", UC_ARM_REG_D2},
                                                      {"D3", UC_ARM_REG_D3},
                                                      {"D4", UC_ARM_REG_D4},
                                                      {"D5", UC_ARM_REG_D5},
                                                      {"D6", UC_ARM_REG_D6},
                                                      {"D7", UC_ARM_REG_D7},
                                                      {"D8", UC_ARM_REG_D8},
                                                      {"D9", UC_ARM_REG_D9},
                                                      {"D10", UC_ARM_REG_D10},
                                                      {"D11", UC_ARM_REG_D11},
                                                      {"D12", UC_ARM_REG_D12},
                                                      {"D13", UC_ARM_REG_D13},
                                                      {"D14", UC_ARM_REG_D14},
                                                      {"D15", UC_ARM_REG_D15},
                                                      {"D16", UC_ARM_REG_D16},
                                                      {"D17", UC_ARM_REG_D17},
                                                      {"D18", UC_ARM_REG_D18},
                                                      {"D19", UC_ARM_REG_D19},
                                                      {"D20", UC_ARM_REG_D20},
                                                      {"D21", UC_ARM_REG_D21},
                                                      {"D22", UC_ARM_REG_D22},
                                                      {"D23", UC_ARM_REG_D23},
                                                      {"D24", UC_ARM_REG_D24},
                                                      {"D25", UC_ARM_REG_D25},
                                                      {"D26", UC_ARM_REG_D26},
                                                      {"D27", UC_ARM_REG_D27},
                                                      {"D28", UC_ARM_REG_D28},
                                                      {"D29", UC_ARM_REG_D29},
                                                      {"D30", UC_ARM_REG_D30},
                                                      {"D31", UC_ARM_REG_D31},
                                                      {"Q0", UC_ARM_REG_Q0},
                                                      {"Q1", UC_ARM_REG_Q1},
                                                      {"Q2", UC_ARM_REG_Q2},
                                                      {"Q3", UC_ARM_REG_Q3},
                                                      {"Q4", UC_ARM_REG_Q4},
                                                      {"Q5", UC_ARM_REG_Q5},
                                                      {"Q6", UC_ARM_REG_Q6},
                                                      {"Q7", UC_ARM_REG_Q7},
                                                      {"Q8", UC_ARM_REG_Q8},
                                                      {"Q9", UC_ARM_REG_Q9},
                                                      {"Q10", UC_ARM_REG_Q10},
                                                      {"Q11", UC_ARM_REG_Q11},
                                                      {"Q12", UC_ARM_REG_Q12},
                                                      {"Q13", UC_ARM_REG_Q13},
                                                      {"Q14", UC_ARM_REG_Q14},
                                                      {"Q15", UC_ARM_REG_Q15},
                                                      {"R0", UC_ARM_REG_R0},
                                                      {"R1", UC_ARM_REG_R1},
                                                      {"R2", UC_ARM_REG_R2},
                                                      {"R3", UC_ARM_REG_R3},
                                                      {"R4", UC_ARM_REG_R4},
                                                      {"R5", UC_ARM_REG_R5},
                                                      {"R6", UC_ARM_REG_R6},
                                                      {"R7", UC_ARM_REG_R7},
                                                      {"R8", UC_ARM_REG_R8},
                                                      {"R9", UC_ARM_REG_R9},
                                                      {"R10", UC_ARM_REG_R10},
                                                      {"R11", UC_ARM_REG_R11},
                                                      {"R12", UC_ARM_REG_R12},
                                                      {"S0", UC_ARM_REG_S0},
                                                      {"S1", UC_ARM_REG_S1},
                                                      {"S2", UC_ARM_REG_S2},
                                                      {"S3", UC_ARM_REG_S3},
                                                      {"S4", UC_ARM_REG_S4},
                                                      {"S5", UC_ARM_REG_S5},
                                                      {"S6", UC_ARM_REG_S6},
                                                      {"S7", UC_ARM_REG_S7},
                                                      {"S8", UC_ARM_REG_S8},
                                                      {"S9", UC_ARM_REG_S9},
                                                      {"S10", UC_ARM_REG_S10},
                                                      {"S11", UC_ARM_REG_S11},
                                                      {"S12", UC_ARM_REG_S12},
                                                      {"S13", UC_ARM_REG_S13},
                                                      {"S14", UC_ARM_REG_S14},
                                                      {"S15", UC_ARM_REG_S15},
                                                      {"S16", UC_ARM_REG_S16},
                                                      {"S17", UC_ARM_REG_S17},
                                                      {"S18", UC_ARM_REG_S18},
                                                      {"S19", UC_ARM_REG_S19},
                                                      {"S20", UC_ARM_REG_S20},
                                                      {"S21", UC_ARM_REG_S21},
                                                      {"S22", UC_ARM_REG_S22},
                                                      {"S23", UC_ARM_REG_S23},
                                                      {"S24", UC_ARM_REG_S24},
                                                      {"S25", UC_ARM_REG_S25},
                                                      {"S26", UC_ARM_REG_S26},
                                                      {"S27", UC_ARM_REG_S27},
                                                      {"S28", UC_ARM_REG_S28},
                                                      {"S29", UC_ARM_REG_S29},
                                                      {"S30", UC_ARM_REG_S30},
                                                      {"S31", UC_ARM_REG_S31},
                                                      {"IPSR", UC_ARM_REG_IPSR},
                                                      {"MSP", UC_ARM_REG_MSP},
                                                      {"PSP", UC_ARM_REG_PSP},
                                                      {"CONTROL", UC_ARM_REG_CONTROL},
                                                      {"IAPSR", UC_ARM_REG_IAPSR},
                                                      {"EAPSR", UC_ARM_REG_EAPSR},
                                                      {"XPSR", UC_ARM_REG_XPSR},
                                                      {"EPSR", UC_ARM_REG_EPSR},
                                                      {"IEPSR", UC_ARM_REG_IEPSR},
                                                      {"PRIMASK", UC_ARM_REG_PRIMASK},
                                                      {"BASEPRI", UC_ARM_REG_BASEPRI},
                                                      {"BASEPRI_MAX", UC_ARM_REG_BASEPRI_MAX},
                                                      {"FAULTMASK", UC_ARM_REG_FAULTMASK},
                                                      {"CP", UC_ARM_REG_CP_REG},
                                                      {"R13", UC_ARM_REG_R13},
                                                      {"R14", UC_ARM_REG_R14},
                                                      {"R15", UC_ARM_REG_R15},
                                                      {"SB", UC_ARM_REG_SB},
                                                      {"SL", UC_ARM_REG_SL},
                                                      {"FP", UC_ARM_REG_FP},
                                                      {"IP", UC_ARM_REG_IP}};

/// A map identifying a Unicorn ARM register size given the register.
inline std::map<arion::REG, uint8_t> ARCH_REGS_SZ = {
    {UC_ARM_REG_R0, 4},      {UC_ARM_REG_R1, 4},          {UC_ARM_REG_R2, 4},        {UC_ARM_REG_R3, 4},
    {UC_ARM_REG_R4, 4},      {UC_ARM_REG_R5, 4},          {UC_ARM_REG_R6, 4},        {UC_ARM_REG_R7, 4},
    {UC_ARM_REG_R8, 4},      {UC_ARM_REG_R9, 4},          {UC_ARM_REG_R10, 4},       {UC_ARM_REG_R11, 4},
    {UC_ARM_REG_R12, 4},     {UC_ARM_REG_R13, 4},         {UC_ARM_REG_R14, 4},       {UC_ARM_REG_R15, 4},
    {UC_ARM_REG_SP, 4},      {UC_ARM_REG_LR, 4},          {UC_ARM_REG_PC, 4},        {UC_ARM_REG_SPSR, 4},
    {UC_ARM_REG_APSR, 4},    {UC_ARM_REG_APSR_NZCV, 4},   {UC_ARM_REG_CPSR, 4},      {UC_ARM_REG_FPSCR, 4},
    {UC_ARM_REG_FPEXC, 4},   {UC_ARM_REG_FPSID, 4},       {UC_ARM_REG_IPSR, 4},      {UC_ARM_REG_IAPSR, 4},
    {UC_ARM_REG_EAPSR, 4},   {UC_ARM_REG_XPSR, 4},        {UC_ARM_REG_EPSR, 4},      {UC_ARM_REG_IEPSR, 4},
    {UC_ARM_REG_MSP, 4},     {UC_ARM_REG_PSP, 4},         {UC_ARM_REG_CONTROL, 4},   {UC_ARM_REG_PRIMASK, 4},
    {UC_ARM_REG_BASEPRI, 4}, {UC_ARM_REG_BASEPRI_MAX, 4}, {UC_ARM_REG_FAULTMASK, 4}, {UC_ARM_REG_S0, 4},
    {UC_ARM_REG_S1, 4},      {UC_ARM_REG_S2, 4},          {UC_ARM_REG_S3, 4},        {UC_ARM_REG_S4, 4},
    {UC_ARM_REG_S5, 4},      {UC_ARM_REG_S6, 4},          {UC_ARM_REG_S7, 4},        {UC_ARM_REG_S8, 4},
    {UC_ARM_REG_S9, 4},      {UC_ARM_REG_S10, 4},         {UC_ARM_REG_S11, 4},       {UC_ARM_REG_S12, 4},
    {UC_ARM_REG_S13, 4},     {UC_ARM_REG_S14, 4},         {UC_ARM_REG_S15, 4},       {UC_ARM_REG_S16, 4},
    {UC_ARM_REG_S17, 4},     {UC_ARM_REG_S18, 4},         {UC_ARM_REG_S19, 4},       {UC_ARM_REG_S20, 4},
    {UC_ARM_REG_S21, 4},     {UC_ARM_REG_S22, 4},         {UC_ARM_REG_S23, 4},       {UC_ARM_REG_S24, 4},
    {UC_ARM_REG_S25, 4},     {UC_ARM_REG_S26, 4},         {UC_ARM_REG_S27, 4},       {UC_ARM_REG_S28, 4},
    {UC_ARM_REG_S29, 4},     {UC_ARM_REG_S30, 4},         {UC_ARM_REG_S31, 4},       {UC_ARM_REG_D0, 8},
    {UC_ARM_REG_D1, 8},      {UC_ARM_REG_D2, 8},          {UC_ARM_REG_D3, 8},        {UC_ARM_REG_D4, 8},
    {UC_ARM_REG_D5, 8},      {UC_ARM_REG_D6, 8},          {UC_ARM_REG_D7, 8},        {UC_ARM_REG_D8, 8},
    {UC_ARM_REG_D9, 8},      {UC_ARM_REG_D10, 8},         {UC_ARM_REG_D11, 8},       {UC_ARM_REG_D12, 8},
    {UC_ARM_REG_D13, 8},     {UC_ARM_REG_D14, 8},         {UC_ARM_REG_D15, 8},       {UC_ARM_REG_D16, 8},
    {UC_ARM_REG_D17, 8},     {UC_ARM_REG_D18, 8},         {UC_ARM_REG_D19, 8},       {UC_ARM_REG_D20, 8},
    {UC_ARM_REG_D21, 8},     {UC_ARM_REG_D22, 8},         {UC_ARM_REG_D23, 8},       {UC_ARM_REG_D24, 8},
    {UC_ARM_REG_D25, 8},     {UC_ARM_REG_D26, 8},         {UC_ARM_REG_D27, 8},       {UC_ARM_REG_D28, 8},
    {UC_ARM_REG_D29, 8},     {UC_ARM_REG_D30, 8},         {UC_ARM_REG_D31, 8},       {UC_ARM_REG_Q0, 16},
    {UC_ARM_REG_Q1, 16},     {UC_ARM_REG_Q2, 16},         {UC_ARM_REG_Q3, 16},       {UC_ARM_REG_Q4, 16},
    {UC_ARM_REG_Q5, 16},     {UC_ARM_REG_Q6, 16},         {UC_ARM_REG_Q7, 16},       {UC_ARM_REG_Q8, 16},
    {UC_ARM_REG_Q9, 16},     {UC_ARM_REG_Q10, 16},        {UC_ARM_REG_Q11, 16},      {UC_ARM_REG_Q12, 16},
    {UC_ARM_REG_Q13, 16},    {UC_ARM_REG_Q14, 16},        {UC_ARM_REG_Q15, 16},      {UC_ARM_REG_CP_REG, 36}};

/// The list of high-level ARM registers that make up the context to be saved and restored.
inline std::vector<arion::REG> CTXT_REGS = {
    UC_ARM_REG_R0,      UC_ARM_REG_R1,      UC_ARM_REG_R2,       UC_ARM_REG_R3,    UC_ARM_REG_R4,   UC_ARM_REG_R5,
    UC_ARM_REG_R6,      UC_ARM_REG_R7,      UC_ARM_REG_R8,       UC_ARM_REG_R9,    UC_ARM_REG_R10,  UC_ARM_REG_R11,
    UC_ARM_REG_R12,     UC_ARM_REG_SP,      UC_ARM_REG_LR,       UC_ARM_REG_PC,    UC_ARM_REG_SB,   UC_ARM_REG_SL,
    UC_ARM_REG_FP,      UC_ARM_REG_IP,      UC_ARM_REG_Q0,       UC_ARM_REG_Q1,    UC_ARM_REG_Q2,   UC_ARM_REG_Q3,
    UC_ARM_REG_Q4,      UC_ARM_REG_Q5,      UC_ARM_REG_Q6,       UC_ARM_REG_Q7,    UC_ARM_REG_Q8,   UC_ARM_REG_Q9,
    UC_ARM_REG_Q10,     UC_ARM_REG_Q11,     UC_ARM_REG_Q12,      UC_ARM_REG_Q13,   UC_ARM_REG_Q14,  UC_ARM_REG_Q15,
    UC_ARM_REG_CPSR,    UC_ARM_REG_APSR,    UC_ARM_REG_SPSR,     UC_ARM_REG_FPSCR, UC_ARM_REG_IPSR, UC_ARM_REG_CONTROL,
    UC_ARM_REG_PRIMASK, UC_ARM_REG_BASEPRI, UC_ARM_REG_FAULTMASK};

/// The ARM Interrupt Descriptor Table
inline std::map<uint64_t, arion::CPU_INTR> IDT = {/*{1, UDEF},
                                           {2, SWI},
                                           {3, PREFETCH_ABORT},
                                           {4, DATA_ABORT},
                                           {5, IRQ},
                                           {6, FIQ},
                                           {7, BKPT},
                                           {8, EXCEPTION_EXIT},
                                           {9, KERNEL_TRAP},
                                           {11, HVC},
                                           {12, HYP_TRAP},
                                           {13, SMC},
                                           {14, VIRQ},
                                           {15, VFIQ},
                                           {16, SEMIHOST},
                                           {17, NOCP},
                                           {18, INVSTATE},
                                           {19, STKOF},
                                           {20, LAZYFP},
                                           {21, LSERR},
                                           {22, UNALIGNED}*/};

/// Unicorn ARM IP and SP registers for genericity.
inline arion::ABI_REGISTERS ABI_REGS = arion::ABI_REGISTERS(UC_ARM_REG_PC, UC_ARM_REG_SP);

/// Unicorn ARM Registers involved in calling convention.
inline arion::ABI_CALLING_CONVENTION ABI_CALLING_CONV =
    arion::ABI_CALLING_CONVENTION(UC_ARM_REG_R0, {UC_ARM_REG_R0, UC_ARM_REG_R1, UC_ARM_REG_R2, UC_ARM_REG_R3});

/// Unicorn ARM Registers involved in syscalling convention.
inline arion::ABI_SYSCALLING_CONVENTION ABI_SYSCALLING_CONV = arion::ABI_SYSCALLING_CONVENTION(
    UC_ARM_REG_R7, UC_ARM_REG_R0,
    {UC_ARM_REG_R0, UC_ARM_REG_R1, UC_ARM_REG_R2, UC_ARM_REG_R3, UC_ARM_REG_R4, UC_ARM_REG_R5, UC_ARM_REG_R6});

/// ARM flags telling the loader which kernel segments should be mapped in memory.
inline arion::KERNEL_SEG_FLAGS SEG_FLAGS = ARION_ARM_TRAPS_PRESENT;

/// Some well working ARM chip HWCAP2 value.
inline uint32_t HWCAP2 = 0;

/// Some well working ARM chip HWCAP value.
inline uint32_t HWCAP = 0x001fb8d7;

/// Size in bytes of a pointer in an ARM chip.
inline const size_t PTR_SZ = 4;

/// Size in bits of the ARM general-purpose registers.
inline const uint16_t ARCH_SZ = 32;

/// Arion CPU_ARCH for ARM.
inline arion::CPU_ARCH ARCH = arion::CPU_ARCH::ARM_ARCH;

/// Multiple architecture specific attributes for ARM, grouped in a structure for genericity purpose.
inline arion::ARCH_ATTRIBUTES ARCH_ATTRS =
    arion::ARCH_ATTRIBUTES(ARCH, ARCH_SZ, PTR_SZ, HWCAP, HWCAP2, SEG_FLAGS, ABI_REGS, ABI_CALLING_CONV,
                           ABI_SYSCALLING_CONV, NAME_BY_SYSCALL_NO);

/// A class responsible for performing architecture specific operations in case of an ARM chip emulation.
class ArchManagerARM : public arion::ArchManager
{
  private:
    /**
     * Interrupt hook used to detect syscalls.
     * @param[in] arion The Arion instance responsible for the interrupt.
     * @param[in] intno The interrupt number.
     * @param[in] user_data Additional user data.
     */
    static void int_hook(std::shared_ptr<arion::Arion> arion, uint32_t intno, void *user_data);
    /**
     * Checks whether the ARM CPU is in ARM or THUMB mode.
     * @return True if the ARM CPU is in THUMB mode.
     */
    bool is_thumb();
    /**
     * Enables the Vector Floating Point (VFP) unit of the ARM emulated chip.
     */
    void enable_vfp();
    /**
     * Prepares the ArchManagerARM for emulation.
     */
    void setup() override;

  public:
    /**
     * Builder for ArchManagerARM instances.
     */
    ArchManagerARM()
        : ArchManager(std::make_shared<arion::ARCH_ATTRIBUTES>(arion_arm::ARCH_ATTRS), arion_arm::ARCH_REGS,
                      arion_arm::ARCH_REGS_SZ, arion_arm::CTXT_REGS, arion_arm::IDT, true) {};

    /** Retrieves a Keystone engine associated with this instance, based on the current mode of the ARM CPU (ARM or
     * THUMB).
     * @return The Keystone engine.
     */
    ks_engine *curr_ks() override;
    /** Retrieves a Capstone engine associated with this instance, based on the current mode of the ARM CPU (ARM or
     * THUMB).
     * @return The Capstone engine.
     */
    csh *curr_cs() override;
    /**
     * Retrieves the current Thread Local Storage (TLS) address from the emulation context.
     * @return The TLS address.
     */
    arion::ADDR dump_tls() override;
    /**
     * Defines a Thread Local Storage (TLS) address to apply to the emulation.
     * @param[in] new_tls The new TLS address.
     */
    void load_tls(arion::ADDR new_tls) override;
    /**
     * Performs ARM specific operations each time emulation starts.
     * @param[in, out] start The emulation start address.
     */
    void prerun_hook(arion::ADDR &start) override;
};

}; // namespace arion_arm

#endif // ARION_ARCH_ARM_HPP
